### ISSUE TITLE
Glewlwyd OpenID Connect plugin - RSA / ECDSA keys not working

### ISSUE THREAD

**Issue by avionbg** [babelouest/glewlwyd#110]
**Describe the issue**
When trying RSA / ECDSA signatures in order to get the jwks working on the jwks_url (some clients heavily relay on that unfortunately) 

**To Reproduce**
Using OpenID connect plugin, following the install instruction - Tried both key with almost all bit lengths in several trials. Steps taken: created the keys with ```openssl genrsa -out private-rsa.key 4096``` and ```openssl ecparam -genkey -name secp521r1 -noout -out private-ecdsa.key```
Added them to the respective file uploads and hit save - Error occurred and daemon exited forcefully with: 

```/usr/bin/glewlwyd: symbol lookup error: /usr/lib/glewlwyd/plugin/libprotocol_oidc.so: undefined symbol: jwt_add_header```

(Jwks was enabled, but i've tried without it also)
**Expected behavior**
Keys would be accepted and changes saved

**Screenshots**
![image](https://user-images.githubusercontent.com/10773370/77243063-c8ef8c80-6c05-11ea-959f-b526267390b5.png)
![image](https://user-images.githubusercontent.com/10773370/77243068-d9076c00-6c05-11ea-9c0c-fbc622775f9b.png)
![image](https://user-images.githubusercontent.com/10773370/77243104-5337f080-6c06-11ea-8528-48ac061e7dc5.png)

**System (please complete the following information):**
 - Ubuntu 18.04.4 LTS
 - Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
 - Glewlwyd 2.1.1
 - Ubuntu packages from release / glewlwyd-full_2.1.1_ubuntu_bionic_x86_64.tar.gz

**Comment by babelouest** [comment]
Hello @avionbg ,

As mentionned in the [install documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#install-glewlwyd-on-ubuntu-1804-lts-bionic), libjwt provided in Ubuntu 18.04 is too old, you must install from the source:

```shell
$ sudo apt install -y pkg-config autoconf libjansson-dev automake make libtool wget
$ wget https://github.com/benmcollins/libjwt/archive/v1.12.0.tar.gz -O libjwt.tar.gz
$ tar -zxvf libjwt.tar.gz
$ cd libjwt-1.12.0
$ autoreconf -i
$ ./configure
$ make && sudo make install
```

**Comment by babelouest** [comment]
Jansson too is too old in Ubuntu 18.04, you must also install it from the source:

```
$ wget https://github.com/akheron/jansson/archive/v2.12.tar.gz -O jansson.tar.gz
$ tar xf jansson.tar.gz
$ cd jansson-2.12
$ autoreconf -i
$ ./configure
$ make
$ sudo make install
```

I will update the documentation accordingly

**Comment by avionbg** [comment]
Yep I did that, I followed the install steps one by one. And I just double checked, the lib is compiled .. only thing is that I can't find where it was installed (I do have make install in history so I must have done that). But I just noticed that I also have older versions of the libjwt installed .. could that be the problem ?

**Comment by avionbg** [comment]
Ah ok .. thanks for the info!

**Comment by babelouest** [comment]
> But I just noticed that I also have older versions of the libjwt installed .. could that be the problem ?

That may be the problem indeed, I've updated the install doc for ubuntu 18.04

Let me know if you still have issues after that

**Comment by avionbg** [comment]
Well at the end I've uninstalled all recompiled packages, cloned the repo and compiled it from scratch. But now I can't login with new users, only the admin works. When I try a newly added one the front just reloads after the login and I can see in the devtools Unauthorized response for profile_list.  Could you give me a hint where to look .. what could be the reason for this ?
Thanks for your great work and your help !

**Comment by avionbg** [comment]
Actually that was my bad, after reinstalling everything I forgot to update cookie domain and that's why it was failing. I see there are now JKW signatures available directly in the clients .. nice !
Again, thank you for all your great job here.

**Comment by babelouest** [comment]
Nice to know!

I'm closing this issue then, feel free to open new one of you find other issues, like with the clients JWT requests.
