### ISSUE TITLE
How to configure to use https accessing Web GUI

### ISSUE THREAD

**Issue by RavilN** [babelouest/glewlwyd#112]
Hi,
Exploring this great looking project and running it in Docker now. Went through documentation and cannot find, how to configure it to use https instead of http. I think support for https is must to have for application which manages sensitive data such as passwords.
Thank you, Ravil

**Comment by babelouest** [comment]
Hello @RavilN ,

As explained in the documentation, you can use Glewlwyd in an https connection using at least 2 ways: https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#ssltls

- Configure Glewlwyd in SSL/TLS mode
- Expose Glewlwyd behind a htps proxy such as apache mod_proxy

I use Glewlwyd behind an apache proxy myself to integrate Glewlwyd in my web environment but both methods will get you Glewlwyd in https mode.
