### ISSUE TITLE
[Issue] Logging out does not properly clear the viewport

### ISSUE THREAD

**Issue by yrammos** [babelouest/glewlwyd#121]
**Describe the issue**
Upon logging out from the user's `/profile.html` page, a number of unnecessary UI controls remain visible and, in some cases, clickable.

**To Reproduce**
Visit your `profile.html` page; log in; log out.

**Expected behavior**
A message unambiguously indicating that the user is logged out, with all irrelevant controls removed from the screen. (Currently the view gives the false impression that the user is still logged in and indeed "Welcome" :)

**Screenshots**
![Screen Shot 2020-06-07 at 5 26 24 PM](https://user-images.githubusercontent.com/1519337/83972216-8fb2e880-a8e7-11ea-8007-6e3f3a1b337a.png)

**System (please complete the following information):**
 - OS/Environment [e.g. Debian Stretch, Ubuntu 19.04]
 - Browser used [e.g. Mozilla Firefox 69, Chrome 77, lynx 2.9]
 - Glewlwyd Version [e.g. 2.0.0, 1.4.9]
 - Source installation [e.g. Distribution package, GitHub package, build from source]
 - If applicable, what option did you use to build Glewlwyd

**Additional context**

**Comment by babelouest** [comment]
Hello @yrammos ,

Thanks for the issue!

Although no effect can be done when the user isn't logged in, having all those controls can make users asking themselves about it and maybe thinking of something bad...

I've fixed the logged out profile page in the [last commit](https://github.com/babelouest/glewlwyd/commit/39882d358f5fe883c00198d4357a345806764ddc), which is now empty except for the top menu, you can test it and give me feedbacks if you want.
