### ISSUE TITLE
In the App GUI, the name and client id fields are interchanged.

### ISSUE THREAD

**Issue by vidcentum** [babelouest/glewlwyd#13]
In the App GUI, the name and client id fields are interchanged.
GUI: Clients
Please refer to Line Numbers 855, 856 - function ClientRow () Line numbers 878, 879

**Comment by babelouest** [comment]
Should be fixed now, thanks

**Comment by vidcentum** [comment]
Thanks, Nicolas.

Best Regards
Maruthi
