### ISSUE TITLE
Cannot setup OIDC plugin

### ISSUE THREAD

**Issue by yrammos** [babelouest/glewlwyd#149]
All attempts to set up an instance of the OIDC plugin fail with a 500 server error or 400 bad request.

After filling out the form with the required parameter and pressing OK, I get a 500 Server Error from Glewlwyd path `api/mod/plugin/oidc2/reset/`

I then repeated from scratch with a new instance and slightly different parameters, this time receiving a 400 Bad Request Error from the same URL path. Glewlwyd expects a numeric value for a field and curiously insists on believing that the type I supply is wrong: `["Property 'request-maximum-exp' is optional and must be a positive integer"]`

I attempted to resolve, albeit unsuccessfully, by removing the last parameter `1` from `onChange={(e) => this.changeParam(e, "request-maximum-exp", 1)}`: https://github.com/babelouest/glewlwyd/blob/c680b1a764cbf4a9c7946bbac5719e098f1a5921/webapp-src/src/Admin/GlwdOIDCParams.js#L1749 

@babelouest Happy to send a list of plugin parameters via a private channel.

**Comment by babelouest** [comment]
Thanks @yrammos , the bug is fixed in the `logout-screen`, I'll add a better error handler tomorrow

**Comment by babelouest** [comment]
The field is more error-proof since https://github.com/babelouest/glewlwyd/commit/cc4d393e0b60545a9eab8402d0084363c82e1973

**Comment by yrammos** [comment]
Thank you, @babelouest, will report back if need be. Closing for now.
