### ISSUE TITLE
You are not authorized to connect to this application

### ISSUE THREAD

**Issue by imperimus** [babelouest/glewlwyd#15]
I have just done a clean Ubuntu 16.04 server build and I got as far as the manager and I am getting: 

You are not authorized to connect to this application

![image](https://cloud.githubusercontent.com/assets/8956183/23718249/a39bda66-042e-11e7-99cf-6fc6f536ec75.png)

If I go to /app/login.html it says I am logged in
![image](https://cloud.githubusercontent.com/assets/8956183/23718150/5e95f492-042e-11e7-98b9-e722ce88e3b0.png)

I am tried putting the webapp in differrent places and a chmod -R a+r, but get the same result. git clone was a couple hours ago so should be up to date.

**Comment by babelouest** [comment]
Hello,

It may be a silly question but do you use the `Log in` button on the top right of the manager to connect to the application, or do you enter manually the `login.html` url?

The proper way is to click the `Log in` Button, then on the login page, click on the button `Continue`, you will be redirected to the manager with a token that will be used to manage the data.

**Comment by babelouest** [comment]
Note that after the redirection, the data will appear after a few seconds.

**Comment by imperimus** [comment]
If i click the login button that is when I get the error:

![image](https://cloud.githubusercontent.com/assets/8956183/23722031/b517b97e-043b-11e7-9178-824640e737da.png)

**Comment by babelouest** [comment]
My bad, I forgot about the file `webapp/init.sql` in the documentation, that's fixed: https://github.com/babelouest/glewlwyd/commit/2e06d62a986748ceaed9973f92c31a2c13bd3600

In you case, simply run the script `webapp/init.sql` in your glewlwyd database, then you'll be able to connect to the application.

Let me know if you have more problems, thanks for the feedback!

**Comment by imperimus** [comment]
Almost nearly :-)

The following needs to be changed to reflect the fqdn/ip to where the server is being hosted.

# login and grant urls
login_url="http://<server>:4593/app/login.html?"
grant_url="http://<server>:4593/app/grant.html?"

With the relevant changes here then it all works.

Fantastic project btw!! only other notes I have from my install on ubuntu 16.04 lts is the following is also required.

apt-get install libtool autoconf

**Comment by babelouest** [comment]
`README.md` updated, thanks for the feedback!
