### ISSUE TITLE
Difficulties using API Keys

### ISSUE THREAD

**Issue by Andy2903** [babelouest/glewlwyd#162]
Hi,

i'm new to this project and I got some difficulties to use API keys. It's not clear to me, how to use the API keys in HTTP requests.

I've tried with `curl 'http://localhost:4593/api/user' -H 'Authorization: Bearer my_api_key' -i` but I always get HTTP 401 error.

Anyone got some ideas what I do wrong?

My environment is running the latest docker container and I can access the website at http://localhost:4593/

Thanks in advance!

**Comment by babelouest** [comment]
Hello @Andy2903 ,

The header prefix value must be `token`, not Bearer.

```shell
$ curl 'http://localhost:4593/api/user' -H 'Authorization: token my_api_key' -i
```

It's explained in the [Getting Started](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#access-to-administration-api-via-api-keys) documentation but I agree that could be improved.

I'll add a message explaining how the API keys can be used in the API key page.

**Comment by Andy2903** [comment]
One more question about the API. In the [API.md](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md#get-all-modules-available) Doc at "Authentication Scheme APIs/HOTP/TOTP authentication scheme/Authentication using scheme" you should enter the otp as string. However the API doesn't accept this and returns 400 Bad Request. Instead it accepts `value` to be a object but won't let me authenticate with a valid otp.
