### ISSUE TITLE
[Issue] Initial Admin Account Doesn't Exist with PostgreSQL

### ISSUE THREAD

**Issue by atsunaakiya** [babelouest/glewlwyd#170]
**Describe the issue**

I used Docker image of glewlwyd and PostgreSQL to build my application.
I initialized the database with [init.postgre.sql](https://github.com/babelouest/glewlwyd/blob/master/docs/database/init.postgre.sql), and launched glewlwyd.
I tried to login with default admin account, username=admin, password=password, but glewlwyd said that Authorization Failed.

A few hours later I recognized that [init.postgre.sql](https://github.com/babelouest/glewlwyd/blob/master/docs/database/init.postgre.sql) actually throws an error at

```sql
INSERT INTO g_user (gu_username, gu_name, gu_password, gu_email, gu_enabled) VALUES ('admin', 'The Administrator', crypt('password', gen_salt('bf')), '', 1);
```

that "gen_salt" doesn't exist.

And turns out that I need to add 
```sql
CREATE EXTENSION pgcrypto;
```
to use "gen_salt".

**To Reproduce**

1. Launch a postgres:9.6 Docker container, and a babelouest/glewlwyd:latest Docker container.
2. Initialize the database with [init.postgre.sql](https://github.com/babelouest/glewlwyd/blob/master/docs/database/init.postgre.sql)
```bash
psql oauth -U user -w -f /sql/postgres.sql
```
3. Try to login

**Expected behavior**

I can login with username=admin and password=password at the first time I launch the website.

**Screenshots**

**System (please complete the following information):**
 - OS/Environment [e.g. Debian Stretch, Ubuntu 19.04] Docker
 - Browser used [e.g. Mozilla Firefox 69, Chrome 77, lynx 2.9] Chrome 77
 - Glewlwyd Version [e.g. 2.0.0, 1.4.9] 2.4.0
 - Source installation [e.g. Distribution package, GitHub package, build from source] None
 - If applicable, what option did you use to build Glewlwyd N/A

**Additional context**

**Comment by babelouest** [comment]
Hello @atsunaakiya ,

It's specified in the [Initialize database](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#initialise-database) documentation that the postgresql database requires the extension pgcrypto:

```
Note: PostgreSQL requires the extension pgcrypto enabled to encrypt users and clients passwords.
```

Were you able to login to glewlwyd after installing the postgre extension?

**Comment by atsunaakiya** [comment]
Hi @babelouest ,
Thank you for replying! (and sorry for late reply)
I should have read the document more carefully...

I'm using it in a Docker container, so I basically recreate the entire db every time I launch the app ...
