### ISSUE TITLE
[Issue] Still getting 401 but no error.

### ISSUE THREAD

**Issue by rperrot** [babelouest/glewlwyd#171]
**Describe the issue**
Hi, 

I built and installed from source glewlwyd, I prepared a postgresql database using the scripts found in doc. I started the server then I went to the homepage. I got this : 

<img width="966" alt="Capture d’écran 2020-11-25 à 08 49 43" src="https://user-images.githubusercontent.com/6479700/100197870-4721d280-2efb-11eb-93e5-b691ca9e7f8c.png">

I then went to the login form and nothing happened.

The log in the console does not show me any error (the login of admin is shown as successful) : 

<img width="1153" alt="Capture d’écran 2020-11-25 à 08 51 38" src="https://user-images.githubusercontent.com/6479700/100197977-73d5ea00-2efb-11eb-9854-c816d24800f5.png">

Did I miss something in the configuration step ? 

**To Reproduce**

1. Build from source
2. Prepare postresql from provided script
3. Run the server

**Expected behavior**

As I saw in the doc I should go back to the home page with additional capabilities (users management, clients management, ...)

**System (please complete the following information):**
 - OS/Environment : 
Raspberry pi 3b+ : 
$ uname -a 
Linux domoticus 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux

 - Browser used [Brave 1.16.76, Chrome 86.0.4240.198]
 - Glewlwyd Version [Current source directory from github]
 - Source installation [build from source]
 - If applicable, what option did you use to build Glewlwyd
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install . ../

**Additional context**

1. glewlwyd is installed in the pi and accessed from other computers in my local network. 
2. I launched the server using command line from the bin folder of the install directory : 
./glewlwyd -l DEBUG -c ../etc/glewlwyd/glewlwyd.conf
3. I modified the configuration file to define the postgresql settings and change the default port. 
4. I installed the pgcrypto from the postgresql-contrib package 
5. I got no error during postgresql configuration (log bellow) 
[db_log.txt](https://github.com/babelouest/glewlwyd/files/5595185/db_log.txt)

**Comment by babelouest** [comment]
Hello @rperrot ,

My best guess is an issue with the [cookie configuration](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#cookies-configuration).

I see you changed the external URL in your config file, have you set your cookie domain to the same hostnamen you use to access glewlwyd?

**Comment by rperrot** [comment]
Yes that's it ! I missed that point. 

Is there a way to inform users (in debug ?) about an incorrect configuration in order to avoid a misconfiguration as I did ?

**Comment by babelouest** [comment]
I guess I could add a debug message if the cookie domain (if set) is different from the external_url domain name.

This kind of error is one of the most that users and I have.

**Comment by babelouest** [comment]
I've added a warning message if the cookie_domain does not match the domain in external_url.

This is not an error message that ends the service, to avoid breaking existing configuration.

**Comment by rperrot** [comment]
Thnaks for your support.
