### ISSUE TITLE
[Issue] Register button not showing up

### ISSUE THREAD

**Issue by gergof** [babelouest/glewlwyd#176]
**Describe the issue**
On the login form the register button doesn't show up.

**To Reproduce**
- Create registration module
- in config.json fill in the `register` field

**Expected behavior**
The button should show up

**Additional context**
The problem is caused by this line: https://github.com/babelouest/glewlwyd/blob/f70a133ea9ff6af6d9ef6bcd504423e8a7c5007d/webapp-src/src/Login/Buttons.js#L205

It should be `this.state.registration`. A possible workaround is to add `"registration": true` into your config.json.

**Comment by babelouest** [comment]
Hello @gergof ,

Did you use the register documentation to install and configure your registration plugin? There's a [paragraph describing](https://github.com/babelouest/glewlwyd/blob/master/docs/REGISTER.md#add-a-link-in-the-login-page) how to update the config.json file.

If this still not work, can you post your `"register"` field from your `config.json` file?

**Comment by gergof** [comment]
Yes, I've followed the description from there.

My config.json register field looks like this:
```json
{
  "register": [{
    "name": "register",
    "message": "login.register-link",
    "reset-credentials-message": "login.reset-credentials-link"
  }]
}
```

**Comment by babelouest** [comment]
Thanks again @gergof , your first assumption was correct, it's probably a regression introduced some time ago. I fixed the bug ere: https://github.com/babelouest/glewlwyd/commit/6a0f7752ec683b4a96bfc4e3f578a4e9147703c1
