### ISSUE TITLE
[Feature request] front-end customization

### ISSUE THREAD

**Issue by yashrajpahwa** [babelouest/glewlwyd#178]
Hi everyone,
I was using the project, and i found it really nice. But is there any way to customize the dashboard that comes prebuilt.
Thanks

**Comment by babelouest** [comment]
Hello @yashrajpahwa ,

The documentation has a [paragraph](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#front-end-application) for the front-end application and customization.

Depending on what changes you need, you can [Customize CSS](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#customize-css), [Customize titles and logos](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#customize-titles-and-logos) or update the [internationalization messages](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#internationalization) or even add a missing language.

If you need deeper changes in the front-end application, you can still personalize the source code to you needs: https://github.com/babelouest/glewlwyd/tree/master/webapp-src

**Comment by yashrajpahwa** [comment]
Hi,
Thanks a ton for the support Nicolas.
Do we have any option to make it headless i.e. having it in the form of API only
If that is available or can be added it would be great 
Thanks

**Comment by babelouest** [comment]
You can disable the entry [static_files_path](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#static-files-path) in your glewlwyd.conf file, like this

```ini
# path to static files for /webapp url
#static_files_path="/usr/share/glewlwyd/webapp/"
```

That way, the front-end application won't be available, only the API:

```shell
$ curl -I http://localhost:4593/
HTTP/1.1 404 Not Found
Connection: Keep-Alive
Content-Length: 80
Content-Type: application/json
Pragma: no-cache
Cache-Control: no-store
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Date: Mon, 05 Apr 2021 15:13:08 GMT
$ curl -s http://localhost:4593/config
{"api_prefix":"api","admin_scope":"g_admin","profile_scope":"g_profile","delete_profile":"no"}
```

The APIs behavior is described in the [API.md](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md) file.

Although, if you choose not to use the front-end, you must at least implement your own [login URL](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#login-url) page.
By default, when the OAuth2 or OIDC plugins auth endpoint isn't accessed with a fully authenticated session and the url parameter `g_continue`, it redirects to the page [external_url](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#external-url)/`login URL` with additional parameters: `client_id`, `scope` and `callback_url`.

You'll have to re-implement all the login schemes you use to make it work, using their [APIs](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md#authentication-scheme-apis), or find another solution compatible with the `login URL` paradigm.

**Comment by yashrajpahwa** [comment]
Thanks for the help @babelouest
