### ISSUE TITLE
[Feature request] Prometheus metrics

### ISSUE THREAD

**Issue by babelouest** [babelouest/glewlwyd#181]
Follow-up of the [conversation](https://github.com/babelouest/glewlwyd/discussions/180) started by @rurus9 .

Glewlwyd would provide a `/api/metric` endpoint that would provide data in prometheus format that would look like

```
# HELP glewlwyd2_oauth2_client_credentials_access_tokens_generated total number of issued tokens
# TYPE glewlwyd2_oauth2_client_credentials_access_tokens_generated counter
glewlwyd2_oauth2_client_credentials_access_tokens_generated 12945
# HELP glewlwyd2_oauth2_client_credentials_access_tokens_forbidden total number of forbidded tokens
# TYPE glewlwyd2_oauth2_client_credentials_access_tokens_forbidden counter
glewlwyd2_oauth2_client_credentials_access_tokens_forbidded 804
```

- The endpoint should be accessible only with an admin session or an [API key](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#access-to-administration-api-via-api-keys) because this data isn't supposed to be public IMO.
- By default `/api/metric` will return all plugin instances data gathered but if specified in the url, the metric can be restricted to one instance: `/api/metric/oidc`
- Should the metric endpoint be able to return only a limited list of metrics if specified? `/api/metric?metric=glewlwyd2_oauth2_client_credentials_access_tokens_generated,glewlwyd2_oauth2_code_generated`

That's the question I can think of at the moment, I'm open to suggestions!

**Comment by rurus9** [comment]
Looking at how I use glewlwyd2 (kubernetes), a separate endpoint with metrics on different port would be the best, something like `:9090/metrics`, with no/optional authorization, so I can expose glewlwyd2 api to the world (by K8s ingress), without exposing metrics (which are scraped by Prometheus running inside the cluster).
  
I think that such a solution would also be convenient for standalone glewlwyd2 instances - you can configure access to metrics e.g using firewall or nginx (depending on how you run glewlwyd2).

> Should the metric endpoint be able to return only a limited list of metrics if specified?

I don't think it is necessary. Prometheus simply expects a endpoint to scraping metrics from.
  
Here is a sample prometheus scraping job configuration (from GitLab <> Prometheus integration: https://docs.gitlab.com/ee/administration/monitoring/prometheus/):
```
  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
      - targets:
        - 1.1.1.1:9168
```

> The one about the metrics should list the metrics you think are useful and what they represent.
> For example, does the metric glewlwyd2_oauth2_client_credentials_access_tokens_forbidden represent when a security event is triggered by an unauthorized client or when an client access_token is wrongly used in an endpoint?

I think these should be two separate metrics

**Comment by babelouest** [comment]
> a separate endpoint with metrics on different port would be the best

Indeed, the metrics endpoint shouldn't be available to the outside world by default, unless the administrator express it.

> I think these should be two separate metrics

So here are the metrics I can think of at the moment:

## General
- number of valid user authentication by scheme
- number of valid user authentication for all schemes
- number of invalid user authentication by scheme
- number of invalid user authentication for all schemes

## OAuth2 plugin
- Number of refresh_token provided, total
- Number of refresh_token provided, per flow
- Number of user access_tokens provided, total
- Number of user access_tokens provided, per flow
- Number of client access_token provided
- Number of unauthorized client access
- Number of invalid code
- Number of invalid refresh_token
- Number of invalid access_tokens at the profile endpoint

## OIDC plugin
- Number of refresh_token provided, total
- Number of refresh_token provided, per flow
- Number of user access_tokens provided, total
- Number of user access_tokens provided, per flow
- Number of id_token provided, total
- Number of id_token provided, per flow
- Number of client access_token provided
- Number of unauthorized client access
- Number of invalid code
- Number of invalid refresh_token
- Number of invalid access_tokens at the endpoint userinfo
- Number of invalid access_tokens at the endpoints introspection, revocation, registration, registration management

**Comment by rurus9** [comment]
I think it's great, maybe something else about the number of errors with access to the backend database (if possible)?

**Comment by babelouest** [comment]
You mean when a function returns `G_ERROR_DB` because the database is unreachable for example? I don't see this fit in the metrics scope but maybe.

I'll also add metrics about registration: number of registered users, lost credentials, profiles deleted

**Comment by babelouest** [comment]
But, considering the metrics values will be stored in the database, I'm not sure the database error metrics value would be relevant...

Have you experienced lots of database error with glewlwyd?

**Comment by alteholz** [comment]
As far as I understand the prometheus counter, you don't need to use a database. Just keep the values in RAM and in case of a glewlwyd restart, start from 0 again (normally you are not interested in the absolute values but in the increase over time).

**Comment by rurus9** [comment]
Exactly, you have four types in prometheus: https://prometheus.io/docs/concepts/metric_types/
For number of assigned tokens et cetera you should use Counter - it is normal in the Prometheus world that the counters are reset when the service is restarted,

**Comment by babelouest** [comment]
OK, let's not store the metrics then, it'll make it easier.

I'll still make the metrics write asynchronous, to minimize the performance issues though.

**Comment by babelouest** [comment]
Hello @rurus9 ,

I've added prometheus metrics in the master branch, can you test it and give me feedbacks?

The documentation to install and use it are available here:
https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#prometheus-metrics-endpoint
https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#prometheus-metrics

**Comment by babelouest** [comment]
Also, let me know if you think other metrics or labels should be added

**Comment by rurus9** [comment]
I built a docker image yesterday with `make docker`
On my test environment it looks great, but there must be a mistake in the default configuration settings.
When I added in /etc/glewlwyd/glewlwyd.conf only:
`metrics_endpoint = true`
then when I try to read the metrics I have 401:
```
curl -v localhost:4594
*   Trying 127.0.0.1:4594...
* Connected to localhost (127.0.0.1) port 4594 (#0)
> GET / HTTP/1.1
> Host: localhost:4594
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Connection: Keep-Alive
< Content-Length: 0
< Date: Wed, 09 Jun 2021 12:23:09 GMT
< 
* Connection #0 to host localhost left intact
```
when I added the whole block:
```
# Prometheus metrics parameters
metrics_endpoint = true # default false
#metrics_bind_address = "127.0.0.1" # default disabled
metrics_endpoint_port = 4594 # default 4594
metrics_endpoint_admin_session = false # default false, if true, then an admin session cookie or a valid API key must be used to authorize access
```
I have an access:
```bash-5.1# curl localhost:4594
# We have seen handsome noble-looking men but I have never seen a man like the one who now stands at the entrance of the gate.
# HELP glewlwyd_auth_user_valid Total number of successful authentication
# TYPE glewlwyd_auth_user_valid counter
glewlwyd_auth_user_valid 0
# HELP glewlwyd_auth_user_valid_scheme Total number of successful authentication by scheme
# TYPE glewlwyd_auth_user_valid_scheme counter
glewlwyd_auth_user_valid_scheme{scheme_type=password} 0
# HELP glewlwyd_auth_user_invalid Total number of invalid authentication
# TYPE glewlwyd_auth_user_invalid counter
glewlwyd_auth_user_invalid 0
# HELP glewlwyd_auth_user_invalid_scheme Total number of invalid authentication by scheme
# TYPE glewlwyd_auth_user_invalid_scheme counter
glewlwyd_auth_user_invalid_scheme{scheme_type=password} 0
```

**Comment by rurus9** [comment]
@babelouest I cannot open this report and did not want to create a new one.
Prometheus does not get metrics, displaying: 

> expected label value, got "INVALID"

I found a tool for checking the correctness of metrics - **promtool**, and it turns out that prometheus is expecting "" in label values.
```
$ cat glewlwyd_metrics
# We have seen handsome noble-looking men but I have never seen a man like the one who now stands at the entrance of the gate.
# HELP glewlwyd_auth_user_valid Total number of successful authentication
# TYPE glewlwyd_auth_user_valid counter
glewlwyd_auth_user_valid 0
# HELP glewlwyd_auth_user_valid_scheme Total number of successful authentication by scheme
# TYPE glewlwyd_auth_user_valid_scheme counter
glewlwyd_auth_user_valid_scheme{scheme_type=password} 0
# HELP glewlwyd_auth_user_invalid Total number of invalid authentication
# TYPE glewlwyd_auth_user_invalid counter
glewlwyd_auth_user_invalid 0
# HELP glewlwyd_auth_user_invalid_scheme Total number of invalid authentication by scheme
# TYPE glewlwyd_auth_user_invalid_scheme counter
glewlwyd_auth_user_invalid_scheme{scheme_type=password} 0
# HELP glewlwyd_oauth2_code Total number of code provided
# TYPE glewlwyd_oauth2_code counter
glewlwyd_oauth2_code{plugin=oauth2} 0
# HELP glewlwyd_oauth2_device_code Total number of device code provided
# TYPE glewlwyd_oauth2_device_code counter
# HELP glewlwyd_oauth2_refresh_token Total number of refresh tokens provided
# TYPE glewlwyd_oauth2_refresh_token counter
glewlwyd_oauth2_refresh_token{plugin=oauth2} 0
glewlwyd_oauth2_refresh_token{plugin=oauth2, response_type=code} 0
glewlwyd_oauth2_refresh_token{plugin=oauth2, response_type=password} 0
# HELP glewlwyd_oauth2_access_token Total number of access tokens provided
# TYPE glewlwyd_oauth2_access_token counter
glewlwyd_oauth2_access_token{plugin=oauth2} 0
glewlwyd_oauth2_access_token{plugin=oauth2, response_type=code} 0
glewlwyd_oauth2_access_token{plugin=oauth2, response_type=password} 0
glewlwyd_oauth2_access_token{plugin=oauth2, response_type=token} 0
glewlwyd_oauth2_access_token{plugin=oauth2, response_type=refresh_token} 0
# HELP glewlwyd_oauth2_client_token Total number of client tokens provided
# TYPE glewlwyd_oauth2_client_token counter
glewlwyd_oauth2_client_token{plugin=oauth2} 162
# HELP glewlwyd_oauth2_unauthorized_client Total number of unauthorized client attempt
# TYPE glewlwyd_oauth2_unauthorized_client counter
glewlwyd_oauth2_unauthorized_client{plugin=oauth2} 0
# HELP glewlwyd_oauth2_invalid_code Total number of invalid code
# TYPE glewlwyd_oauth2_invalid_code counter
glewlwyd_oauth2_invalid_code{plugin=oauth2} 0
# HELP glewlwyd_oauth2_invalid_device_code Total number of invalid device code
# TYPE glewlwyd_oauth2_invalid_device_code counter
# HELP glewlwyd_oauth2_invalid_refresh_token Total number of invalid refresh token
# TYPE glewlwyd_oauth2_invalid_refresh_token counter
glewlwyd_oauth2_invalid_refresh_token{plugin=oauth2} 0
# HELP glewlwyd_oauth2_invalid_acccess_token Total number of invalid access token
# TYPE glewlwyd_oauth2_invalid_acccess_token counter
```
```
$ cat glewlwyd_metrics | promtool check metrics
error while linting: text format parsing error in line 7: expected '"' at start of label value, found 'p'
```
when i changed the 7th line to:
```
glewlwyd_auth_user_valid_scheme{scheme_type="password"} 0
```
I have:
```
error while linting: text format parsing error in line 13: expected '"' at start of label value, found 'p'
```
so for testing I added "" to all label values:
```
# We have seen handsome noble-looking men but I have never seen a man like the one who now stands at the entrance of the gate.
# HELP glewlwyd_auth_user_valid Total number of successful authentication
# TYPE glewlwyd_auth_user_valid counter
glewlwyd_auth_user_valid 0
# HELP glewlwyd_auth_user_valid_scheme Total number of successful authentication by scheme
# TYPE glewlwyd_auth_user_valid_scheme counter
glewlwyd_auth_user_valid_scheme{scheme_type="password"} 0
# HELP glewlwyd_auth_user_invalid Total number of invalid authentication
# TYPE glewlwyd_auth_user_invalid counter
glewlwyd_auth_user_invalid 0
# HELP glewlwyd_auth_user_invalid_scheme Total number of invalid authentication by scheme
# TYPE glewlwyd_auth_user_invalid_scheme counter
glewlwyd_auth_user_invalid_scheme{scheme_type="password"} 0
# HELP glewlwyd_oauth2_code Total number of code provided
# TYPE glewlwyd_oauth2_code counter
glewlwyd_oauth2_code{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_device_code Total number of device code provided
# TYPE glewlwyd_oauth2_device_code counter
# HELP glewlwyd_oauth2_refresh_token Total number of refresh tokens provided
# TYPE glewlwyd_oauth2_refresh_token counter
glewlwyd_oauth2_refresh_token{plugin="oauth2"} 0
glewlwyd_oauth2_refresh_token{plugin="oauth2", response_type="code"} 0
glewlwyd_oauth2_refresh_token{plugin="oauth2", response_type="password"} 0
# HELP glewlwyd_oauth2_access_token Total number of access tokens provided
# TYPE glewlwyd_oauth2_access_token counter
glewlwyd_oauth2_access_token{plugin="oauth2"} 0
glewlwyd_oauth2_access_token{plugin="oauth2", response_type="code"} 0
glewlwyd_oauth2_access_token{plugin="oauth2", response_type="password"} 0
glewlwyd_oauth2_access_token{plugin="oauth2", response_type="token"} 0
glewlwyd_oauth2_access_token{plugin="oauth2", response_type="refresh_token"} 0
# HELP glewlwyd_oauth2_client_token Total number of client tokens provided
# TYPE glewlwyd_oauth2_client_token counter
glewlwyd_oauth2_client_token{plugin="oauth2"} 162
# HELP glewlwyd_oauth2_unauthorized_client Total number of unauthorized client attempt
# TYPE glewlwyd_oauth2_unauthorized_client counter
glewlwyd_oauth2_unauthorized_client{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_invalid_code Total number of invalid code
# TYPE glewlwyd_oauth2_invalid_code counter
glewlwyd_oauth2_invalid_code{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_invalid_device_code Total number of invalid device code
# TYPE glewlwyd_oauth2_invalid_device_code counter
# HELP glewlwyd_oauth2_invalid_refresh_token Total number of invalid refresh token
# TYPE glewlwyd_oauth2_invalid_refresh_token counter
glewlwyd_oauth2_invalid_refresh_token{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_invalid_acccess_token Total number of invalid access token
# TYPE glewlwyd_oauth2_invalid_acccess_token counter
```
and now:
```
$ cat glewlwyd_metrics | promtool check metrics
glewlwyd_auth_user_invalid counter metrics should have "_total" suffix
glewlwyd_auth_user_invalid_scheme counter metrics should have "_total" suffix
glewlwyd_auth_user_valid counter metrics should have "_total" suffix
glewlwyd_auth_user_valid_scheme counter metrics should have "_total" suffix
glewlwyd_oauth2_access_token counter metrics should have "_total" suffix
glewlwyd_oauth2_client_token counter metrics should have "_total" suffix
glewlwyd_oauth2_code counter metrics should have "_total" suffix
glewlwyd_oauth2_invalid_code counter metrics should have "_total" suffix
glewlwyd_oauth2_invalid_refresh_token counter metrics should have "_total" suffix
glewlwyd_oauth2_refresh_token counter metrics should have "_total" suffix
glewlwyd_oauth2_unauthorized_client counter metrics should have "_total" suffix
```
so it turns out that label values ​​should be with "", moreover, counter metrics should have suffix _total

**Comment by babelouest** [comment]
@rurus9 , as mentioned in the [install doc](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#prometheus-metrics-endpoint), the prometheus endpoint is disabled by default, because unless I'm told the opposite, this feature isn't useful for every users.

So to avoid data leaks and performance drops, this feature must be explicitly enabled.

Although, there is a small bug with the config value `metrics_endpoint_admin_session` which should be disabled by default, not the opposite, I'll fix that shortly.

Thanks for the feedback with the labels values with quotes and the suffix to add, I'll make the change as well.

No need to open a new issue for those, we can continue to discuss prometheus in this thread, even if the bug is closed.

**Comment by babelouest** [comment]
@rurus9 , can you test with the last commits to check if the metrics are readable now?

**Comment by rurus9** [comment]
@babelouest 
I checked and now it's clean (great work, thank you!):
```
$ cat glewlwyd_metrics
# We have seen handsome noble-looking men but I have never seen a man like the one who now stands at the entrance of the gate.
# HELP glewlwyd_auth_user_valid_total Total number of successful authentication
# TYPE glewlwyd_auth_user_valid_total counter
glewlwyd_auth_user_valid_total 0
# HELP glewlwyd_auth_user_valid_scheme_total Total number of successful authentication by scheme
# TYPE glewlwyd_auth_user_valid_scheme_total counter
glewlwyd_auth_user_valid_scheme_total{scheme_type="password"} 0
# HELP glewlwyd_auth_user_invalid_total Total number of invalid authentication
# TYPE glewlwyd_auth_user_invalid_total counter
glewlwyd_auth_user_invalid_total 0
# HELP glewlwyd_auth_user_invalid_scheme_total Total number of invalid authentication by scheme
# TYPE glewlwyd_auth_user_invalid_scheme_total counter
glewlwyd_auth_user_invalid_scheme_total{scheme_type="password"} 0
# HELP glewlwyd_oauth2_code_total Total number of code provided
# TYPE glewlwyd_oauth2_code_total counter
glewlwyd_oauth2_code_total{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_device_code_total Total number of device code provided
# TYPE glewlwyd_oauth2_device_code_total counter
# HELP glewlwyd_oauth2_refresh_token_total Total number of refresh tokens provided
# TYPE glewlwyd_oauth2_refresh_token_total counter
glewlwyd_oauth2_refresh_token_total{plugin="oauth2"} 0
glewlwyd_oauth2_refresh_token_total{plugin="oauth2", response_type="code"} 0
glewlwyd_oauth2_refresh_token_total{plugin="oauth2", response_type="password"} 0
# HELP glewlwyd_oauth2_access_token_total Total number of access tokens provided
# TYPE glewlwyd_oauth2_access_token_total counter
glewlwyd_oauth2_access_token_total{plugin="oauth2"} 0
glewlwyd_oauth2_access_token_total{plugin="oauth2", response_type="code"} 0
glewlwyd_oauth2_access_token_total{plugin="oauth2", response_type="password"} 0
glewlwyd_oauth2_access_token_total{plugin="oauth2", response_type="token"} 0
glewlwyd_oauth2_access_token_total{plugin="oauth2", response_type="refresh_token"} 0
# HELP glewlwyd_oauth2_client_token_total Total number of client tokens provided
# TYPE glewlwyd_oauth2_client_token_total counter
glewlwyd_oauth2_client_token_total{plugin="oauth2"} 132
# HELP glewlwyd_oauth2_unauthorized_client_total Total number of unauthorized client attempt
# TYPE glewlwyd_oauth2_unauthorized_client_total counter
glewlwyd_oauth2_unauthorized_client_total{plugin="oauth2"} 22
# HELP glewlwyd_oauth2_invalid_code_total Total number of invalid code
# TYPE glewlwyd_oauth2_invalid_code_total counter
glewlwyd_oauth2_invalid_code_total{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_invalid_device_code_total Total number of invalid device code
# TYPE glewlwyd_oauth2_invalid_device_code_total counter
# HELP glewlwyd_oauth2_invalid_refresh_token_total Total number of invalid refresh token
# TYPE glewlwyd_oauth2_invalid_refresh_token_total counter
glewlwyd_oauth2_invalid_refresh_token_total{plugin="oauth2"} 0
# HELP glewlwyd_oauth2_invalid_acccess_token_total Total number of invalid access token
# TYPE glewlwyd_oauth2_invalid_acccess_token_total counter
```
```
$ cat glewlwyd_metrics | promtool check metrics
$
```
From my point of view, metrics that count errors in SQL would also be useful, with a malfunctioning mariadb instance glewlwyd logged:
```
2021-06-09T15:08:37Z - Glewlwyd ERROR: Error executing sql query
2021-06-09T15:08:37Z - Glewlwyd DEBUG: Error message: "Lost connection to MySQL server during query"
2021-06-09T15:08:37Z - Glewlwyd DEBUG: Query: "SELECT gcmi_module AS module, gcmi_name AS name, gcmi_display_name AS display_name, gcmi_parameters, gcmi_order AS order_rank, gcmi_readonly, gcmi_enabled FROM g_client_module_instance WHERE 1=1 ORDER BY gcmi_order "
```
I assume the number of occurrences of` "Glewlwyd ERROR: Error executing sql query"` would be sufficient?
Thanks again ;)

**Comment by babelouest** [comment]
I've added database errors in the metrics in the [last commit](https://github.com/babelouest/glewlwyd/commit/fd8dda112fcebc3224096bce4b1861936299ff59)

**Comment by rurus9** [comment]
@babelouest 
I built a docker image and test it, everything works.
Prometheus scrobes metrics without complaining (and e.g. Grafana is able to draw graphs based on this, alarms can be set, etc.)
Great job, and the quote is excellent
`We have seen handsome noble-looking men but I have never seen a man like the one who now stands at the entrance of the gate.`
Thank you.

**Comment by babelouest** [comment]
Awesome, let's close this issue now, geek free to open new ones if needed!
