### ISSUE TITLE
[Issue] No protocol for endpoints in openid discovery data

### ISSUE THREAD

**Issue by dguihal** [babelouest/glewlwyd#187]
**Describe the issue**

Currently trying to setup glewlwyd with traefik-forward-auth client using openid plugin

I'm facing a strange bug

On glewlwyd openid configuration side I have :

```
URL openid-configuration for this instance https://glewlwyd.host/api/openid/.well-known/openid-configuration
URL API Auth for this instance https://glewlwyd.host/api/openid/auth
URL API Token for this instance https://glewlwyd.host/api/openid/token
URL userinfo for this instance https://glewlwyd.host/api/openid/userinfo
```

But on the openid-configuration json file I have:

```json
{
  "issuer":"https://glewlwyd.host/api/openid",
  "authorization_endpoint":"glewlwyd.host/api/openid/auth",
  "token_endpoint":"glewlwyd.host/api/openid/token",
  "userinfo_endpoint":"glewlwyd.host/api/openid/userinfo",
  "jwks_uri":"glewlwyd.host/api/openid/jwks"
```

what is missing is url scheme on endpoint urls thus the redirect forward thinks it is a path a not a full URL

**To Reproduce**

Install the openid plugin a get auto config url

**Expected behavior**

I would expect having full urls in data field like

```
  "authorization_endpoint":"https://glewlwyd.host/api/openid/auth",
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4045744/130138819-ca8df1ca-5fa5-4bf8-bd66-b3c9aa7cc062.png)
![image](https://user-images.githubusercontent.com/4045744/130139166-c3d02f04-1c43-4dd3-b3cd-d8e5e9bcf87e.png)

**System (please complete the following information):**
 - OS/Environment  Docker image: babelouest/glewlwyd               2.5.3            22f73d344f61
 - Browser used curl ;)
 - Glewlwyd Version 2.5.3
 - Source installation docker hub
 - If applicable, what option did you use to build Glewlwyd N/A

**Additional context**

**Comment by dguihal** [comment]
OK got the answer:

GLWD_EXTERNAL_URL must be a full URL (with protocol) and not just the hosname

not a bug then

**Comment by babelouest** [comment]
Hello,

The discovery endpoint URLs are based on your `external_url`, my insight is that you set this value without the protocol.

https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#external-url

**Comment by babelouest** [comment]
@dguihal , the bug is that it could be clearer in the documentation, I'll amend that.
