### ISSUE TITLE
[Windows] Cannot add user on a fresh install

### ISSUE THREAD

**Issue by sfhacker** [babelouest/glewlwyd#193]
Just built lastest version from source on Windows 10 x64.
Started the server. I can login successfully and add a new user DB backend.

![image](https://user-images.githubusercontent.com/25817529/153674098-8a518d41-b90f-4571-82be-b3a916d36525.png)

 However I can't add a new user.

![image](https://user-images.githubusercontent.com/25817529/153674354-0e221c47-9387-4c02-98a0-7ff799ffa44f.png)

I suspect I may have missed some setup or details.

![image](https://user-images.githubusercontent.com/25817529/153674424-5c20fd05-1ccf-4db1-afe1-79198478428b.png)

Any hints would be grateful.

Cheers.

**Comment by babelouest** [comment]
I'm confusing with your issue. You say you can't add a new user, but the screenshot right after shows a invalid connection screen. Which one is it?

If it's an add user issue, you may have more information in the API call.
Open the javascript console (usually press [F12]), try to add a user, then in the network tab, look at the `POST http://localhost:4593/api/user` call, and check the response, it will tell you the response status and body.

**Comment by sfhacker** [comment]
Thanks for the debugging tip! Cool.

This is what I get when I click on the 'OK' button.

![image](https://user-images.githubusercontent.com/25817529/153679611-3b50cefe-8e2b-43c5-b9ab-bb858340eb64.png)

**Comment by babelouest** [comment]
Hello @sfhacker ,

any update on this issue?
