### ISSUE TITLE
[Windows] Enabling SSL feature

### ISSUE THREAD

**Issue by sfhacker** [babelouest/glewlwyd#194]
Fresh install, latest version.

Whenever enable ssl on the server, I see the following same error message on the console. Tried to debug it to no avail.

# TLS/SSL configuration values
use_secure_connection=true
secure_connection_key_file="D:/SSO_Server/etc/certs/server.key"
secure_connection_pem_file="D:/SSO_Server/etc/certs/server.crt"
secure_connection_ca_file="D:/SSO_Server/etc/certs/root1.crt"

![image](https://user-images.githubusercontent.com/25817529/153676455-8a885bb8-c4b5-454c-94f3-4443c55f002a.png)

Thanks.

**Comment by babelouest** [comment]
Hi,

It seems you didn't change the `external_url` value and you're accessing glewlwyd via an `http` connection, not an `https`.
You should change your `external_url` value to `"https://localhost:4593"` in the config file and access this url instead of the `http` one.

**Comment by babelouest** [comment]
Hello @sfhacker ,

any update on this issue?
