### ISSUE TITLE
[Feature request] User roles

### ISSUE THREAD

**Issue by timmotw** [babelouest/glewlwyd#196]
**Is your feature request related to a problem? Please describe.**
This feature is closely related to what we have [discussed previously](https://github.com/babelouest/glewlwyd/issues/184). We would like to have roles with related scopes under them. For example: A user having `Role A`, will automatically have the related scopes to that role. A user will be able to belong to several roles.

**Describe the solution you'd like**
We would like to have a new module or extend the current user module to allow the configuration of roles and their respective scopes.

**Describe alternatives you've considered**
Could we develop a middle-ware module which decorates the user with the configured role set and respective scope union set, related to the roles? Would that be future proof when it comes to the `g_user` table?

**Additional context**
![Database Schema](http://www.plantuml.com/plantuml/svg/bPBBJiCm44Nt_ef1R1f1L-nGw5UmjrnxabWuTZHZGr7LVoTfGY0lLBASkJuvkZQ_MTyeKZNKmGTTKQWH8YKKF6ugvSq7sHZHzojnPx2mlWsgeyFTAGFj53ES8CzXz_fuNnHuB9uoE1n4PGr2ZR4AXeNe3vIIa4CYZP9rQ323iu3sEnSMdRd0GqaihPdCIbfChfcB43yuoFTxcDFX6OBlpyFBm2c7rHzv7lBNlupY6xwy8kTLZVEPGTPacsY3xyp7Ee9RAs41JIlGD87ELieOsysLamsrvXG_vRjoQS50twcOYTJGoYrYj296ss8a4zbv0LlTfd--XHRrVQyZzOOtCC_-llyl)

**Comment by babelouest** [comment]
The way I see it, you have 2 options:
- update the [user database backend](https://github.com/babelouest/glewlwyd/blob/master/src/user/database.c) to add some features to match your roles with scopes
- create a [user middleware module](https://github.com/babelouest/glewlwyd/tree/master/src/user_middleware) to upgrade users with new scopes depending on the roles they belong to.

Both of them are very specific to your needs, and depends on your data model, I won't have the time to develop it. But you can give it a try, and I can provide some support then.

**Comment by timmotw** [comment]
@babelouest thank you very much for the feedback! The other option would be to consider roles and scopes as the same thing and make the action authorization checks at the software component level in a way that Java Spring or .NET does it in a declarative way (through annotations speechifying the allowed roles) but in our case with C++ this will be done manually meaning programmatically.

[Dave Syer (the leader of the Spring Security OAuth2 project) says that roles and scopes are just arbitrary strings that might be considered as the same thing.](https://stackoverflow.com/questions/22417780/using-scopes-as-roles-in-spring-security-oauth2-provider). This is also mentioned in [OAuth 2.0 Cookbook](https://www.packtpub.com/product/oauth-2-0-cookbook/9781788295963).

**Comment by babelouest** [comment]
Glewlwyd's security model is based on scopes only, by design.

I agree roles are similar to scopes in some cases, but to make the implementation easier, and to avoid complexity that would lead to bugs or security issue, I prefer to stick on the security model as it is now.

Nevertheless, as you said, adding a module to support your role data model shouldn't be too hard.

**Comment by timmotw** [comment]
@babelouest thank you very much. I will post any questions I might have. I noticed that there is a `g_scope_group` table. Is this used anywhere?

**Comment by babelouest** [comment]
The table `g_scope_group` is a link table between a scope and an authentication scheme: https://github.com/babelouest/glewlwyd/blob/master/docs/database/init.mariadb.sql#L169

You can see it in action in the [scope add modal](https://github.com/babelouest/glewlwyd/blob/master/docs/screenshots/scope-add.png), in there you can add multiple scope groups, each group have a list of schemes required and a number of scheme required by group.

![https://github.com/babelouest/glewlwyd/raw/master/docs/screenshots/scope-add.png](https://github.com/babelouest/glewlwyd/raw/master/docs/screenshots/scope-add.png)

**Comment by timmotw** [comment]
@babelouest we are integrating with Envoy [OAuth2 HTTP filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) in order for the proxy to do the checks and remove this concern from the client and also backend (apart from HMAC check I guess). I want to associate the gRPC Resource URIs with scopes so that Glewlwyd will check the requested resource and approve or not. I guess this will be achieved through the Resource Indicators (RFC 8707) supported by the OpenID Connect plugin.

I will try to make this dynamic by extracting the requested recourse at the envoy point and forwarding it in the list of requested resources to be checked against the list of granted scopes.

Do you believe I am looking at the right direction concerning RFC 8707?

**Comment by babelouest** [comment]
Hello @timmotw ,

I'm not sure I understand what you're trying to achieve with this, unfortunately, I don't know `OAuth2 HTTP filter`.
The goal of the RFC 8707 is to use the `resource` parameter as the `aud` value in the access token claims or the introspection result, so the client can bind an access token to a specific resource server for example.
If you want OAuth2 HTTP filter to support resource parameters, I suggest you ask them to, it will be easier.

**Comment by timmotw** [comment]
Hi @babelouest 

I had in mind something similar to this [answer](https://stackoverflow.com/questions/42186537/resources-scopes-permissions-and-policies-in-keycloak)

What I am trying to achieve is to be able to relate a resource with a scope (and in my case the scope related to a role as well); so if a user tries to access a resource which is not related to her/his assigned scopes, to prevent it as unauthorized resource access.

**Comment by timmotw** [comment]
> Hi @timmotw ,
> 
> If you want to bind a scope to one or multiple resource addresses, you already can in the plugin configuration page.
> 
> For example, you enable resource indicators, and you setup `scope1` and `scope2` to allow some resources: ![image](https://user-images.githubusercontent.com/3966617/168598728-e70b00c7-8ed2-4a79-a714-af5969566c1f.png)
> 
> If a client is requesting https://resource1.tld/ with the scope `scope2`, Glewlwyd will return the following error: `error=invalid_target`
> 
> Unless I didn't understand your goal, that's what you're looking for right?

@babelouest  yes this is what I am after. I did not understand your previous comment well.

**Comment by timmotw** [comment]
@babelouest the scopes drop-down is disabled. Do I need to enable something else first?

![image](https://user-images.githubusercontent.com/524466/169020118-e82b96c8-d9f2-4d47-b043-fd828831af85.png)

**Comment by babelouest** [comment]
Did you enable "allow resources indicators"?

**Comment by timmotw** [comment]
Yes as the picture above

**Comment by timmotw** [comment]
Can the resource `URIs` be relative or for each requested resource through a different `IP`/`Host-name` I need to add the specific 
`IP`/`Host-name` that can be assigned to the machine?

e.g.

https://locahost/resource1
https://127.0.0.1/resource1
https://192.168.10.1/resource1

**Comment by timmotw** [comment]
When you say fragment you mean the following are not legal? 

https://127.0.0.1/api/v2/package.ConfigurationService/read_config
https://127.0.0.1/api/v2/package.DataService/clean_sessions

They are accepted from the Glewlwyd UI

**Comment by babelouest** [comment]
Yes, the fragment is the `#...` part at the end of the URI

**Comment by timmotw** [comment]
I tried the following:

1. **Chrome - Version 101.0.4951.64 (Official Build) (64-bit)** - NOT WORKING
2. Chromium - Version 101.0.4951.64 (Official Build) snap (64-bit)
3. Firefox - 100.0 (64-bit)

I did not see any error in the javascript console

**Comment by timmotw** [comment]
OK I noticed that the scopes are missing from the the drop-down in Chrome:

![image](https://user-images.githubusercontent.com/524466/169108481-0666dbce-bde7-4de8-b256-9eb100680d99.png)

whereas in Chromium:

![image](https://user-images.githubusercontent.com/524466/169108656-5788b5a2-4af0-427c-85fc-dadf5075043c.png)

**Comment by timmotw** [comment]
@babelouest I added 2-3 resources only, but still the resources I did not add are accessible for the client app.

Does the client need to send the resource parameter? I tried that as well to be honest. I checked the RFC8707 a bit but still the resource verification is not kicking in.

**Comment by babelouest** [comment]
Yes, according to the [RFC8707](https://datatracker.ietf.org/doc/html/rfc8707#section-2.1), you must set the resource parameter in the `/auth` request, something like:

```
     GET /as/authorization.oauth2?response_type=token
        &client_id=example-client
        &state=XzZaJlcwYew1u0QBrRv_Gw
        &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
        &resource=https%3A%2F%2Fapi.example.com%2Fapp%2F HTTP/1.1
```

When the access token is received, the resource parameter will be set in the `aud` claim of the AT or the introspection response.

**Comment by timmotw** [comment]
@babelouest I will refer to a project other than Glewlwyd because I am missing some point here.

1. According to the RFC8707 the client app. states the list of resources it accesses
2. The Glewlwyd OIDC module allows to bind the client app. scope specific resources
3. If the user attempts to access any other resource than the user's assigned scopes resource list, Glewlwyd will respond with the error `invalid_target  The requested resource is invalid, missing, unknown, or malformed.`

Now I am using [Envoy's OAuth2 fillter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) which as I see forwards the `resource` parameter values to Glewlwyd and they are correctly listed:

1. In the Envoy's configuration yaml
2. In the OIDC module instance configuration

Here is what actually happens:

Even if I added only 2 allowed resources (in both envoy and OIDC configs), and more resources are requested by the client app. by the configured ones; I get no `invalid_target` error.

**Comment by babelouest** [comment]
Hi @timmotw ,

Usually, it's hard to understand the problem with so few information. Can you post the `/auth` url generated by [Envoy's OAuth2 fillter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/oauth2_filter) and received by glewlwyd?

Also, note that Glewlwyd supports only one resource parameter, even if the RFC states that multiple resources parameters is possible. I may change that in a future release.

**Comment by timmotw** [comment]
@babelouest 

`https://127.0.0.1/sso/api/oidc/auth?client_id=ui&scope=global&response_type=code&redirect_uri=https://127.0.0.1/api/v2/callback&state=http://127.0.0.1/api/v2/pack.ConfigService/read&resource=http://127.0.0.1/api/v2/pack.ConfigService/version&resource=http://127.0.0.1/api/v2/pack.DataService/read_customers`

> Also, note that Glewlwyd supports only one resource parameter, even if the RFC states that multiple resources parameters is possible. I may change that in a future release.

I think your statement above renders it a blocker for me and I will need to find another way to authorize each resource at the API level.

**Comment by babelouest** [comment]
How the RFC deals with multiple resource values is not crystal clear, but here's how I understand it:

- The client can use multiple resource parameters in the `/auth` request only, with the response type `code` only
- When requesting an access token based on the code or the refresh token, the client must specify a resource parameter that is previously used in the `/auth` request
- If the client uses multiple resource parameters for the token response type, the AS will reject the request

**Comment by timmotw** [comment]
@babelouest  thank you very much for the clear explanation

**Comment by babelouest** [comment]
Hello @timmotw ,

Can you test the master branch? I've updated the resource indicator as I explain it above.

**Comment by timmotw** [comment]
> Hello @timmotw ,
> 
> Can you test the master branch? I've updated the resource indicator as I explain it above.

Hi @babelouest I will test it over the weekend most prob. Thank you!

**Comment by babelouest** [comment]
The new feature has been introduced in the [release 2.7.1](https://github.com/babelouest/glewlwyd/releases/tag/v2.7.1), happy hacking!

**Comment by timmotw** [comment]
@babelouest Thank you very much!
