### ISSUE TITLE
[Issue] OIDC plugin prevents changing the session cookie name

### ISSUE THREAD

**Issue by ghost** [babelouest/glewlwyd#198]
**Describe the issue**
Configuring the OIDC module prevents custom session id name, un-checking ends up with value NaN which still cannot be overridden

**To Reproduce**

1. Go to `Parameters` | `Plugins` | `Add`
2. Select` OpenID Connect`
3. Fill up the mandatory fields
4. Check `Allow session management endpoints`
5. Try to change the `OIDC session cookie name` value. It does not allow it
6. Un-check Allow session management endpoints`  you get a `NaN` as the value

**Expected behavior**
To be allowed to change the value to a custom value such as `SEC_OIDC_SID` etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/524466/165311394-69661f99-21ef-4df2-a3cd-8e67b28d4a5d.png)

**System (please complete the following information):**
OS/Environment Ubuntu 20.04
Browser used [e.g. Mozilla Firefox 69, Chrome 77, lynx 2.9]
Glewlwyd Version 2.6.2
Source installation Docker image (Docker hub)

**Comment by babelouest** [comment]
Hello @timmotw ,

Indeed, thanks for noticing. I'll make the fix soon, it will be available in the 2.7 release.
