### ISSUE TITLE
Support for SameSite Cookies

### ISSUE THREAD

**Issue by a1730** [babelouest/glewlwyd#204]
**Describe the issue**
We have a test that currently fails with Google Chrome clients due to missing SameSite setting.

**To Reproduce**
Connect to Glewlwyd as any user. Check glewlwyd cookies using browsers' developer tool. You will notice missing SameSite cookie setting, or, `curl -c - 'http://glewlwyd.tld'`

**Expected behavior**
SameSite cookie attribute is set

**Screenshots**

**System (please complete the following information):**
 - OS/Environment [Debian bullseye]
 - Browser used [ Mozilla Firefox 100.0 64bit, Chrome Version 101.0.4951.54 (Official Build) (32-bit)]
 - Glewlwyd Version [2.7.0]
 - Source installation [GitHub debian package]
 - If applicable, what option did you use to build Glewlwyd [N/A]

**Additional context**
N/A

**Comment by a1730** [comment]
Hello @babelouest ,

Thank you for the quick accomodation.
You might want to bring glewlwyd into compliance with [rfc-6265 section-5.4](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-09#section-5.4) while you re modifying this code path. I belive you are halfway there already. [INSTALL.md](https://github.com/babelouest/glewlwyd/blob/cf25a6c26fa6de0bcc2f547b15c5b95233127203/docs/INSTALL.md) currently has documentation for cookie_secure and cookie_domain.

Thank you again for the excellent support Nicolas!

**Comment by babelouest** [comment]
When you mention `I believe you are halfway there.`, do you mean you only need the `SameSite` value or do you expect other values?

**Comment by a1730** [comment]
Hi,
We would be ticked pink if you could add other values.

I opened the issue for SameSIte because that was what we picked up in our failed test.
In short, we could use SameSite right away but it would help us if you can implement other values.

To be clear, this is not a production issue. We are in the process of testing Glewlwyd for push to production.

Thank you for you attention, and time - most important.

**Comment by babelouest** [comment]
Hello @a1730 ,

The `cookie_same_site` property has been added in the config file.

```
# glewlwyd.conf
# cookie_same_site, to set the SameSite value in the cookies, values available are 'empty' (no SameSite value), 'none', 'lax' or 'strict', default 'empty'
cookie_same_site="empty"
```

It's not released yet but you can test it by building glewlwyd with the git repository for glewlwyd and its dependencies. Especially, ulfius has been updated to support `SameSite=None` but this change isn't released yet.

**Comment by a1730** [comment]
Hello @babelouest.

Thank you for glewlwyd. We appreciate you.
