### ISSUE TITLE
Can we use  glewlwyd as bridging for other SSO services?

### ISSUE THREAD

**Issue by vampiebar** [babelouest/glewlwyd#209]
Hello,
Is it possible to use glewlwyd as bridge for other Oauth2/openID services..

Our App ( such as nextcloud ) ---> glewlwyd.  ---> facebook login

so our app will be logged in from glewlwyd with facebook...?

**Comment by babelouest** [comment]
Hello,

You have the [OAuth2 scheme](https://github.com/babelouest/glewlwyd/blob/master/docs/OAUTH2_SCHEME.md) that may help you. Using this scheme, you can login on a Glewlwyd instance using another account on another OAuth2 service.

Nevertheless, the OAuth2 scheme isn't the best maintained scheme, and I don't use it myself.

Also consider that Glewlwyd as it is, a personal project: https://github.com/babelouest/glewlwyd#disclaimer
So be careful on how you use it.
