### ISSUE TITLE
glewlwyd attempts to log in as root to mysql server despite different data provided

### ISSUE THREAD

**Issue by danielw1990** [babelouest/glewlwyd#211]
So during the setup it asks for credentials for mysql.
I provide them and then it fails because it attempts a root login without password. According to itself. Well, of course that fails, I never asked it to do that and that account needs a password. 
Which I was never asked to provide and don't see the need for.

What is going on here? Why does it attempt to log in as root into the mysql server during the installation process?

**Comment by babelouest** [comment]
This doesn't seem right, what installation process are you using? Is it installed via a distribution package?

**Comment by danielw1990** [comment]
I installed it via the package manager of Ubuntu 20.04.5 LTS.

**Comment by babelouest** [comment]
I don't know what causes your issue, but don't use the root MySQL user to run glewlwyd (you already know that).

You can for example install the package without installing the database, then manually install the database based on the [install documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#initialise-database), use the database scripts that should be available in /usr/doc/glewlwyd, not the one from this repo, they are not up to date.

Or you can open an issue at Ubuntu, they may help you better then I.

**Comment by babelouest** [comment]
Also note that glewlwyd 1.x is deprecated for a long time, and not recommended to be used in production.

**Comment by danielw1990** [comment]
Oh, okay, So I will try again after the dist upgrade.

glewlwyd Version 1.4.9
