### ISSUE TITLE
[Issue] Possible config check bug

### ISSUE THREAD

**Issue by roquie** [babelouest/glewlwyd#214]
**Describe the issue**
`config != NULL` check after using config

https://github.com/babelouest/glewlwyd/blob/fc56978428cf62a8b551e934050f878ae0829ce9/src/plugin.c#L88-L89

vs 

https://github.com/babelouest/glewlwyd/blob/fc56978428cf62a8b551e934050f878ae0829ce9/src/plugin.c#L62

**Comment by babelouest** [comment]
Fixed in https://github.com/babelouest/glewlwyd/commit/dfe0086bdb4c2f2932519d7d262c9c93896dae8c , thanks!
