### ISSUE TITLE
[Issue] Memory leaks

### ISSUE THREAD

**Issue by roquie** [babelouest/glewlwyd#215]
**Describe the issue**
A memory leaks while using server.

**To Reproduce**
1. Copy-paste docker command with latest version then run
2. In other terminal tab run `docker stats`
3. Open UI, login as admin, goto page with users list
4. Press and hold F5 (or Ctrl/Cmd + R) 5-15 sec. Can repeat this action 5-10 times.
5. Look at memory, step 2. It increases and after some time of typical usage don't flush.

**Expected behavior**
May be is a normal behavior 🥲

**Comment by babelouest** [comment]
Hello,

I don't think it's a memory leak, I've checked the docker stat result with your input, and the memory increases to 3/4 MB and then stalls there, I think it's the docker behavior.
