### ISSUE TITLE
[Security request] Registration plugin: Update password without entering old password is insecure

### ISSUE THREAD

**Issue by roquie** [babelouest/glewlwyd#216]
**Is your feature request related to a problem? Please describe.**
An attacker can steal access token / cookie (XSS) and [send API request](https://github.com/babelouest/glewlwyd/blob/master/docs/REGISTER.md#update-password) to change password without knowing old password. 

**Describe the solution you'd like**
1. API should require `old_password` json-field for updating password 
2. Validate old password with password stored in database (if exists).
3. Otherwise return 400 http status code

**Comment by babelouest** [comment]
Hello,

The update password in the registration plugin is a [reset credentials](https://github.com/babelouest/glewlwyd/blob/master/docs/REGISTER.md#reset-credentials-process) feature, it's supposed to be used by the user if it has forgotten its password. To authenticate in this page, the user must use a link send to its e-mail, or use a previously saved recovery code, depending on the plugin configuration.

There is an update password feature in the [profile page](https://github.com/babelouest/glewlwyd/blob/master/docs/USER.md#password), where the user must be authenticated and must enter its current password to update it.
