### ISSUE TITLE
fail to launch

### ISSUE THREAD

**Issue by fro0m** [babelouest/glewlwyd#22]
hi, I got the problem with lib ulfius. May be you know what is the problem 
```
sudo ./glewlwyd --config-file=glewlwyd.conf
./glewlwyd: error while loading shared libraries: libulfius.so: cannot open shared object file: No such file or directory
```

ulfius is installed from git (make install output)
```
cp libulfius.so.2.0 /usr/local/lib
cp ulfius.h /usr/local/include
ldconfig -r /usr/local

```

**Comment by babelouest** [comment]
Sometimes the command `ldconfig -r` executed at the end of the install process won't work as expected. To reload all the new libraries, run the following command:
```bash
$ sudo ldconfig
```
Then relaunch glewlwyd, this should fix your problem.

I will update the Makefiles, thanks for reporting.

**Comment by fro0m** [comment]
yes, it worked. thank you for support
