### ISSUE TITLE
Docker Image for arm64

### ISSUE THREAD

**Issue by jiatao99** [babelouest/glewlwyd#220]
**Is your feature request related to a problem? Please describe.**
Run  `sudo docker run --rm -it -p 4593:4593 babelouest/glewlwyd:latest` and got this error

```bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /entrypoint.sh: exec format error
```

**Describe the solution you'd like**
Can you please build a docker image for arm64?

**Describe alternatives you've considered**
Tried to build the image by change Dockerfile to:  `FROM arm64v8/alpine:latest AS builder` and got this error

```
#44 16.58 CMake Error at CMakeLists.txt:134 (find_package):
#44 16.58   By not providing "FindOrcania.cmake" in CMAKE_MODULE_PATH this project has
#44 16.58   asked CMake to find a package configuration file provided by "Orcania", but
#44 16.58   CMake did not find one.
#44 16.58
#44 16.58   Could not find a package configuration file provided by "Orcania"
#44 16.58   (requested version 2.3.3) with any of the following names:
#44 16.58
#44 16.58     OrcaniaConfig.cmake
#44 16.58     orcania-config.cmake
```

**Comment by babelouest** [comment]
Hello,

I've updated the docker image builders, now you should be able to build an alpine image from the source

**Comment by jiatao99** [comment]
Thanks. I am able to build and run the arm64 image. 

However I got this error: Error in config file, contact your administrator

My docker is sitting behind Nginx Proxy Manager and forward the https request to http://glewlwyd:4593. This piece seems working fine. 

I also followed doc to modify the config file as following

1. external_url="https://<my domain name>/"
2. cookie_domain="<my domain name>"

Can you please advice which portion needs to be modified?

Thanks again
