### ISSUE TITLE
Login with default credentials does not work

### ISSUE THREAD

**Issue by fro0m** [babelouest/glewlwyd#23]
After build and configuring up, login with following credentials
admin
password

Does not work. Authorisation page says that login/password is incorrect.

And one other question is what is the rationale of using LDAP?

**Comment by babelouest** [comment]
Hi,

I'm gonna need more information to help you.
What system/OS are you using?
What backend database?
Did you run properly the SQL command to create the admin user and add the the scope `g_admin` and `g_profile`?
Did you run the script `webapp/init.sql` ?

Also, I don't understand t your last at question, what do you mean by 'rationale'?

**Comment by babelouest** [comment]
Hello @fro0m ,

Any update on your issue?

**Comment by fro0m** [comment]
hi, i am not able to test it anymore

**Comment by babelouest** [comment]
Hi,

OK, so I'll close this issue then. You can reopen it if necessary in the future.
