### ISSUE TITLE
So I have the Server Setup

### ISSUE THREAD

**Issue by haroot** [babelouest/glewlwyd#24]
now how do I access it with my node app? these are my values and how I access github Oauth2
How can I get my client id and secret using the Oauth2 server? Sorry I am noob to Oauth2 but I got your server running including jwt and db by Readme.md and Install.md. Will make a deb for it for you soon!

  client: {
    idParamName: 'client_id', // client_id
    secretParamName: 'client_secret', // client_secret
    // github - working
    id: 'xxxxxxxxxxxxxxxxxxx',
    secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  }
  auth: {
    // github - working
    tokenHost: 'https://github.com',
    tokenPath: '/login/oauth/access_token',
    authorizePath: '/login/oauth/authorize',
  },
  http: {
    headers: { Accept: 'application/json' , },
  },
  options: {
    bodyFormat: 'form', // form or json
    useBasicAuthorizationHeader: 'true',
    useBodyAuth: 'true',
  },
var authorizationUri = oauth2.authorizationCode.authorizeURL({
  redirect_uri: 'https://comain.com/callback',
  scope: 'notifications', //github - working
  state: 'XXXXXX', //hidden for security
});

**Comment by babelouest** [comment]
Hi @haroot ,

I don't know the application you try to use with glewlwyd, and I guess its name isn't "node app" but I'll try to help you configure and use Glewlwyd.

Very basically, a OAuth2 server is used to delegate user authentication and authorization, so a third-party application (the client) can access resources owned by the user. The workflow looks like this for the user:
Go to the client url, ex: [http://my-client-app.domain/](http://my-client-app.domain/), redirect to glewlwyd authentication page with parameters to validate the connection, ex: [http://auth.domain/auth?response_type=token&client_id=x&scope=y&redirect_uri=http://my-client-app.domain/](http://auth.domain/auth?response_type=token&client_id=x&scope=y&redirect_uri=http://my-client-app.domain/), if the user is authenticated and authorized, redirect to `redirect_uri` with a token or a code in the url parameter so the client can access resources owned by the user.

This means you must have a client record properly defined in glewlwyd admin page, this client record must have those 4 parameters properly defined:
- `response_type`: token or code/authorization code in most cases
- `client_id`: the client_id you will choose, must be unique in your glewlwyd config
- `scope`: one or many scope that are required by your client application. The scope must be previously created in the `scope` tab, and the user must have access to at least one of the specified scope
- `redirect_uri`: the uri of the client that glewlwyd will redirect to when the connection is successful

To use a new client application with glewlwyd, you must first add it in the client tab in the admin page of glewlwyd, llike [http://localhost:4593/app/](http://localhost:4593/app/)

Screens look like this:
![client tab](https://github.com/babelouest/glewlwyd/blob/master/screenshots/g_3_clients.png)
![new/update client](https://github.com/babelouest/glewlwyd/blob/master/screenshots/g_3_clients_update.png)

The client_id value must be unique and is most probably the parameter client.id in your client config file.
You must set the authorization type properly, although I don't have a clue which one your application uses, probably `token`, if this doesn't work, try adding `code` and `authorization code` too.
The scope value is important too, this corresponds to your `oauth2.authorizationCode.authorizeURL.scope` value most likely.
Then, finally, a valid redirection_uri must be added, this is the url of your client application that catches the token value or the code when your connection to glewlwyd is successful.

Then you must configure properly your client application to be used with glewlwyd.
- The parameter `secretParamName` is the client password, you can set one in glewlwyd for confidential clients, although you may not need it, check the client documentation.
- `tokenHost` is the url of your glewlwyd server, like `http://auth.domain`
- `tokenPath` is the relative path to the token address, `/token/` in glewlwyd case
- `authorizePath` is the relative path to the auth address, `/auth/` in glewlwyd case
- `bodyFormat` must be probably `form` for glewlwyd
- `useBasicAuthorizationHeader` and `useBodyAuth` can be set to `false` if you don't use client authentication
- Finally, `redirect_uri` and `scope` are to be set with your settings

**Comment by babelouest** [comment]
Hi @haroot , any luck on your issues?

**Comment by haroot** [comment]
Havn't tried yet implemented MySQL Login first then OAuth2

**Comment by babelouest** [comment]
@haroot , any update?

**Comment by haroot** [comment]
went a different route but ill contact you when I enable it in the future

**Comment by babelouest** [comment]
ok, I'm closing the bug then
