### ISSUE TITLE
[feature request] MFA support

### ISSUE THREAD

**Issue by vixns** [babelouest/glewlwyd#30]
Please consider supporting U2F and TOTP.

These two libraries may help :
https://github.com/Yubico/libu2f-server
https://github.com/paolostivanin/libcotp

**Comment by babelouest** [comment]
oooohhhh a challenge!

U2F is quite cryptic to me, I understand the goals, but the implementation and the use case on the server-side is not easy-peasy,
I'll go deeper through the documentation but some help would be very useful.
I imagine you have the need for this, so if you can describe how you imagine U2F to be implemented in Glewlwyd, that would be great. A pull request would be even better.

TOTP seems more doable, I have to figure out on how to implement this in Glewlwyd with the scopes and stuff, if you have clues for that too, I wouldn't mind.

I think it's an excellent candidate for the next major release of Glewlwyd, where new types of authentication backends will be easier to implement.

**Comment by babelouest** [comment]
Hello @vixns ,

Glewlwyd 2.0.0 Beta 1 is now released, you can now authenticate with multiple authentication schemes, including TOTP and Yubikeys via Webauthn.

I invite you to take a look at this new version and give me feedbacks if you want.
