### ISSUE TITLE
Ubuntu 14.04 build

### ISSUE THREAD

**Issue by alpha0010** [babelouest/glewlwyd#40]
Thought I would share what I found necessary to build under Ubuntu 14.04.
```bash
sudo apt-get install libcurl4-gnutls-dev uuid-dev libldap2-dev libsqlite3-dev libconfig-dev libgnutls-dev libssl-dev libmysqlclient-dev libtool autoconf

wget https://github.com/akheron/jansson/archive/v2.11.tar.gz
tar -xf v2.11.tar.gz
cd jansson-2.11
autoreconf -i
./configure
make
sudo make install
cd ..

git clone https://github.com/benmcollins/libjwt.git
cd libjwt
autoreconf -i
./configure
make
sudo make install
cd ..

git clone https://github.com/babelouest/orcania.git
cd orcania/src
make static
sudo make static-install
cd ../..

git clone https://github.com/babelouest/yder.git
cd yder/src
make Y_DISABLE_JOURNALD=1 CPPFLAGS=-DY_DISABLE_JOURNALD static
sudo make static-install
cd ../..

git clone https://github.com/babelouest/ulfius.git
cd ulfius/src
make static
sudo make static-install
cd ../..

git clone https://github.com/babelouest/hoel.git
cd hoel/src
make DISABLE_POSTGRESQL=1 static
sudo make static-install
cd ../..

wget http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.59.tar.gz
tar -xf libmicrohttpd-0.9.59.tar.gz
cd libmicrohttpd-0.9.59
./configure
make
sudo make install
cd ..

git clone https://github.com/babelouest/glewlwyd.git
cd glewlwyd/src
make LDFLAGS="-lmicrohttpd -lcurl -lsqlite3 `mysql_config --libs_r` -Wl,-rpath -Wl,/usr/local/lib"
```

**Comment by babelouest** [comment]
Thanks,

This looks like you build librairies as static, is there a reason?

**Comment by alpha0010** [comment]
If I did not, the later make commands would fail to link to them since the .so install does not include a non-versioned link target.  Building static meant I did not need to edit any of the install scripts.

**Comment by babelouest** [comment]
OK, got it, I added a build error by mistake in the last releases, that's why you (nor anyone as far as I know) can't link to the libraries.

The cmake build or the generated packages seem fine though.

I'll make a patch asap to fix this.

Thanks for pointing out

**Comment by alpha0010** [comment]
Thanks.  Build works with shared now.  (This means that the last line in the above build script can be changed to simply `make`.)

The only problem is:
```
~/glewlwyd-build/ulfius/src$ sudo make uninstall 
rm -f /usr/local/lib/libulfius.so libulfius.a
rm -f /usr/local/lib/libulfius.so.*
rm -f /usr/local/include/ulfius.h
```
The static library is not properly removed.

**Comment by babelouest** [comment]
Thanks for pointing out, this has been fixed in https://github.com/babelouest/ulfius/commit/e45c0d80a853380f5201ef872e6678f9d095082c
