### ISSUE TITLE
How do you change web app front?

### ISSUE THREAD

**Issue by cyclonstep** [babelouest/glewlwyd#46]
Hello, In these past three days I've been wanting to redesign your web app front based on my needs. I created my own code base using react and not in the default directory. But when i tried to fetch with url =>(e.g : http://localhost:4593/app/auth/user), i found that in my redesigned web app the results that action was 403 forbidden. Why did it end up like this? or is glewlwyd can only accept request from the directory that have been set up before in glewlwyd.conf ? Your answer is very much appreciated! thank you!

**Comment by babelouest** [comment]
Hello,

All the front-end files are located in the [webapp/](https://github.com/babelouest/glewlwyd/tree/master/webapp) directory:

- [Login page](https://github.com/babelouest/glewlwyd/blob/master/webapp/login.html)
- [Grant access page](https://github.com/babelouest/glewlwyd/blob/master/webapp/grant.html)
- [Reset password page](https://github.com/babelouest/glewlwyd/blob/master/webapp/reset.html)
- [Administration application](https://github.com/babelouest/glewlwyd/blob/master/webapp/index.html)
- [User profile application](https://github.com/babelouest/glewlwyd/blob/master/webapp/profile.html)

All of those pages are Single Page Application using Javascript, they all use the APIs located in `/api`.

Most of the APIs require a valid bearer token provided by Glewlwyd.
When you call an API within your web application, you must add this token in the header.
You can see how the API calls are made [here](https://github.com/babelouest/glewlwyd/blob/master/webapp/app/glewlwyd.react.js#L94) for example.

The full API documentation is available [there](https://github.com/babelouest/glewlwyd/blob/master/docs/API.md).

You can redesign the front-end pages as much as you want.

**Comment by babelouest** [comment]
The install documentation has been updated accordingly.

**Comment by cyclonstep** [comment]
Hey, sorry for just replying this thread late. Thanks for your answers. It helped me to set up my front end to integrate with yours. Can I ask another question within this thread? Where can i get a valid token once the user logged in? I tried to read the response from '/auth/user' but it seems that I only get status ok from it.  I read the API docs but it only said that the response containing valid token.  Thank you
