### ISSUE TITLE
Webapp's login.html is not rendered...

### ISSUE THREAD

**Issue by vidcentum** [babelouest/glewlwyd#5]
1) I am able to build glewlwyd with dependencies and the server is run.

Console log of the glewlwyd server:
2017-03-04T18:41:06 - Glewlwyd INFO: Starting Glewlwyd Oauth2 authentication service
2017-03-04T18:41:06 - Glewlwyd INFO: Start glewlwyd on port 4593, prefix: oauth, secure: false

2) When I tried to load the login_url, (http://localhost/oauth/login.html?), the login page is not displayed. It failed with http://localhost/config - file not found.  

@babelouest, I am new to glewlwyd. Please help me in running the app.

**webapp/login.html**
```
window.onload = function () {
		params = getQueryParams(location.search);
    $.get("../config/", function (result) {
      api_prefix = result.api_prefix;
      checkUser();
    });
};
```

**Comment by babelouest** [comment]
@vidcentum , no problem.

By default, Glewlwyd isn't listening on port 80 but 4593, so you probably should try the url [http://localhost:4953/](http://localhost:4953/), this should redirect to the `app` url which is [http://localhost:4953/app/](http://localhost:4953/app/) if you have th default configuration, check your `glewlwyd.conf` file for the values:
https://github.com/babelouest/glewlwyd/blob/master/glewlwyd.conf.sample#L20

**Comment by vidcentum** [comment]
Thanks, @babelouest . I tried that. I was getting the {"resource not found":"/app/"} error. 
Please bear with me; I am trying to get handle on the application flow.

**Comment by babelouest** [comment]
in your config file, you have the `static_files_path` that points to the the path of the administration app:
https://github.com/babelouest/glewlwyd/blob/master/glewlwyd.conf.sample#L17

By default it's `"/var/www"` but it must match the path to your app folder, maybe something like:
`/home/pi/glewlwyd/webapp` or `<path_to_your_glewlwyd_source_code>/webapp`.

**Comment by babelouest** [comment]
you must restart glewlwyd if you change the config file

**Comment by babelouest** [comment]
Documentation improved: https://github.com/babelouest/glewlwyd/commit/373d873570f81350a00224777404ea8e428fc409
Thanks @vidcentum for the comment!

**Comment by vidcentum** [comment]
Thank you @babelouest . I am now able to see the index.html.

**Comment by babelouest** [comment]
Awesome! If you're ok you can close this issue, feel free to open new ones if you have other problems

**Comment by vidcentum** [comment]
Thanks, a lot. I will keep you updated on the findings. 
Having gone through the code and its structure, you have done a great job! It is clean and very fast as well.

**Comment by haroot** [comment]
if you get error {"resource not found":"/webapp/"}

config as so

# url prefix
url_prefix="glewlwyd"

# path to static files for /webapp url
static_files_path="/var/www/webapp"

# static files prefix
static_files_prefix = "app"

change url prefix to domain ?

**Comment by babelouest** [comment]
Hi @haroot ,

your problems don't seem to be related to those issues you're sending comments to, can you open a new issue for your problem?
