### ISSUE TITLE
glewlwyd.conf.sample typo

### ISSUE THREAD

**Issue by xava-charlesj** [babelouest/glewlwyd#54]
It serves me right to just copy the sample config and edit, but there's a typo on:

refresh_token_expiation.

It's missing the r.

It's all good though, only spent about 2 days finding it :-)

**Comment by babelouest** [comment]
Thanks for the issue,

I've been told about this typo a few weeks ago. I added a comment about that in the config sample file it in the [branch 1.4](https://github.com/babelouest/glewlwyd/blob/1.4/docs/glewlwyd.conf.sample#L89).

But I can't fix the parameter name in Glewlwyd 1.x without risking to break existing installations. So the typo will stay... :-(

**Comment by babelouest** [comment]
_"Fixed"_ in https://github.com/babelouest/glewlwyd/commit/c0f66ad76520f06935ea6440ba2fb84a56a6b305
