### ISSUE TITLE
webapp not working again

### ISSUE THREAD

**Issue by yandoogle** [babelouest/glewlwyd#58]
Hello, Nicolas.
I am trying to manage glewlwyd 2.0.0-b2 using webapp on fresh debian "buster" system, but it`s not working for me right now.

After login page with admin/password it was an error:
![изображение](https://user-images.githubusercontent.com/1921271/60885827-8ba6c280-a261-11e9-8561-3405198d39ab.png)

If I trying to add new scope or something else:
![изображение](https://user-images.githubusercontent.com/1921271/60886059-0d96eb80-a262-11e9-9f1a-c8a89231f620.png)

On browser console you can see the following error message and 401 http code - unauthorized:
> _XML Parsing Error: no root element found
> Location: http://tarqeq.vpn:4593/api/scope?offset=0&limit=20
> Line Number 1, Column 1:

my configs

glewlwyd.conf                                     
external_url="http://tarqeq.vpn:4593"                                                                                                                                                                       
login_url="login.html"                                                                                
url_prefix="api"                                                                                            
static_files_path="/usr/local/share/glewlwyd/webapp/" 
...

config.json
"GlewlwydUrl": "http://tarqeq.vpn:4593/",
"ProfileUrl": "http://tarqeq.vpn:4593/profile.html",
"AdminUrl": "http://tarqeq.vpn:4593/index.html",
"LoginUrl": "http://tarqeq.vpn:4593/login.html"
...

So that it could be?
Thanks.

**Comment by babelouest** [comment]
Hello,

My best guess is that you use a http connection instead of https, and the cookie isn't stored by your browser because it has the `secure` flag on.

You can use glewlwyd in https mode by enabling the config option `use_secure_connection=true`, or by using it behind a https reverse proxy.

If you can't or don't want to use glewlwyd in https mode, you can try to recompile glewlwyd with the option `INSECURE_COOKIE`:

```shell
glewlwyd/build$ cmake -DINSECURE_COOKIE=off ..
glewlwyd/build$ make
```

**Comment by babelouest** [comment]
I'll add warning messages in the next beta to avoid this confusion

**Comment by yandoogle** [comment]
Thanks for the quick reply!
Using the https mode solved my problem.
