### ISSUE TITLE
Error Connecting Glewlwyd API

### ISSUE THREAD

**Issue by aviezab** [babelouest/glewlwyd#60]
Hello Nicolas Mora,
I have tried this latest glewlwyd from INSTALL.md (https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md)
both compiling from source, and using .deb package has this error, accessing / , /login.html, and all possible routes.

![image](https://user-images.githubusercontent.com/34294278/62539338-34efd100-b87f-11e9-8098-fb5ec2bd41f5.png)

This is ```glewlwyd.conf``` for ```--config-file``` args, mainly copy from sample included.
```
#
#
# Glewlwyd SSO Authorization Server
#
# Copyright 2016-2019 Nicolas Mora <mail@babelouest.org>
# Gnu Public License V3 <http://fsf.org/>
#
#

# port to open for remote commands
port=4593

# external url to access to this instance
external_url="http://MY_IP:4593"

# login url relative to external url
login_url="login.html"

# url prefix
url_prefix="api"

# path to static files for /webapp url
# static_files_path="/usr/share/glewlwyd/webapp/"
static_files_path="/ssoserver/webapp/"

# access-control-allow-origin value
allow_origin="*"

# log mode (console, syslog, journald, file)
log_mode="console"

# log level: NONE, ERROR, WARNING, INFO, DEBUG
log_level="DEBUG"

# output to log file (required if log_mode is file)
# log_file="/var/log/glewlwyd.log"
log_file = "/ssoserver/build/logglewlwyd.log"

# cookie domain
# cookie_domain="localhost"

# cookie_secure, this options SHOULD be set to 1, set this to 0 to test glewlwyd on insecure connection http instead of https
cookie_secure=0

# session expiration, default is 4 weeks
session_expiration=2419200

# session key
session_key="GLEWLWYD2_SESSION_ID"

# admin scope name
admin_scope="g_admin"

# profile scope name
profile_scope="g_profile"

# user_module path
# user_module_path="/usr/lib/glewlwyd/user"
user_module_path="/ssoserver/build/_user"

# client_module path
# client_module_path="/usr/lib/glewlwyd/client"
client_module_path="/ssoserver/build/_client"

# user_auth_scheme_module path
# user_auth_scheme_module_path="/usr/lib/glewlwyd/scheme"
user_auth_scheme_module_path= "/ssoserver/build/_scheme"

# plugin_module path
# plugin_module_path="/usr/lib/glewlwyd/plugin"
plugin_module_path="/ssoserver/build/_plugin"

# TLS/SSL configuration values
use_secure_connection=false
secure_connection_key_file="/etc/ssl/certs/cert.key"
secure_connection_pem_file="/etc/ssl/certs/cert.pem"
secure_connection_ca_file="/etc/ssl/certs/ca.crt"

# Algorithms available are SHA1, SHA256, SHA512, MD5, default is SHA256
hash_algorithm = "SHA512"

# MariaDB/Mysql database connection
database =
{
  type     = "mariadb"
  host     = "localhost"
  user     = "glewlwyd"
  password = "glewlwyd"
  dbname   = "glewlwyd"
  port     = 3306
};

# mime types for webapp files
static_files_mime_types =
(
  {
    extension = ".html"
    mime_type = "text/html"
  },
  {
    extension = ".css"
    mime_type = "text/css"
  },
  {
    extension = ".js"
    mime_type = "application/javascript"
  },
  {
    extension = ".json"
    mime_type = "application/json"
  },
  {
    extension = ".png"
    mime_type = "image/png"
  },
  {
    extension = ".jpg"
    mime_type = "image/jpeg"
  },
  {
    extension = ".jpeg"
    mime_type = "image/jpeg"
  },
  {
    extension = ".ttf"
    mime_type = "font/ttf"
  },
  {
    extension = ".woff"
    mime_type = "font/woff"
  },
  {
    extension = ".woff2"
    mime_type = "font/woff2"
  },
  {
    extension = ".map"
    mime_type = "application/octet-stream"
  },
  {
    extension = ".ico"
    mime_type = "image/x-icon"
  }
)

```

This is the screenshot I running using .deb package:
![image](https://user-images.githubusercontent.com/34294278/62539732-20f89f00-b880-11e9-9e10-9bd9b361ae5e.png)

and this is running using source-compiled binary:
![image](https://user-images.githubusercontent.com/34294278/62539794-45ed1200-b880-11e9-8ae6-19fbb65cc64d.png)

Could You tell me, maybe there is step I missed?
The default 4093 is automatically run the web UI, doesn't it?
Thanks

**Comment by babelouest** [comment]
Hello @aviezab ,

This is probably an error in your file `webapp/config.json`. The webapp tries to access the API via the URL `http://localhost:4593/` on your browser, but it seems you installed Glewlwyd in another machine than localhost.
In your file `/ssoserver/webapp/config.json`, the first lines look probably like this:

```JSON
{
  "GlewlwydUrl": "http://localhost:4593/",
  "ProfileUrl": "http://localhost:4593/profile.html",
  "AdminUrl": "http://localhost:4593/index.html",
  "LoginUrl": "http://localhost:4593/login.html",
```

Replace the occurences of `http://localhost:4593` with what you put in the `external_url` variable in your `glewlwyd.conf` and that should do it.

**Comment by aviezab** [comment]
![image](https://user-images.githubusercontent.com/34294278/62545163-6078b880-b88b-11e9-80bb-e5be8f7845e0.png)

It works.
Thanks Nico.

The Installation readme should be updated. Let me do the pull request. I have tested on Arch Linux too, can I write also how to for Arch Linux?

**Comment by babelouest** [comment]
There is already a paragraph about the font-end application in the [install documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#front-end-application).

But if you find a better way to document the instllation, I'm open to it!

Concerning the Arch linux installation, I'm interested in improving the documentation to explain it for Arch users. Thanks!

**Comment by aviezab** [comment]
@babelouest Ah, I didn't understand what the config part xD
I got it now.
Thanks Nico!

**Comment by babelouest** [comment]
I'll close this issue then, feel free to open a pull request to improve the documentation if you feel like it.
