### ISSUE TITLE
First connection to the administration page is empty

### ISSUE THREAD

**Issue by pixelblender** [babelouest/glewlwyd#62]
Hi,

My system is Ubuntu server 18.04. I've downloaded and compiled `glewlwyd-2.0.0-b3` and went with `make && sudo make install`.

Then I did `sqlite3 /var/cache/glewlwyd/glewlwyd.db < docs/database/init.sqlite3.sql` and of course I made sure the path is writable by `sudo chown -R me:me /var/cache/glewlwyd/`.

In the `/usr/local/etc/glewlwyd/glewlwyd.conf` the database setting is:
```
external_url="http://my_public_ip:4593"
# ...
database =
{
  type = "sqlite3"
  path = "/var/cache/glewlwyd/glewlwyd.db"
};
```

In the `/usr/local/share/glewlwyd/webapp/config.json`:
```
"GlewlwydUrl": "http://my_public_ip:4593/",
"ProfileUrl": "http://my_public_ip:4593/profile.html",
"AdminUrl": "http://my_public_ip:4593/index.html",
"LoginUrl": "http://my_public_ip:4593/login.html",
```

Then I ran `glewlwyd` as my priv `glewlwyd --config-file=/usr/local/etc/glewlwyd/glewlwyd.conf --log_mode=console --log-level=DEBUG`

But the administrator page is nothing like the `GETTING STARTED` page, it's empty. And logger doesn't says anything about it.

![Screen Shot 2019-08-27 at 1 44 30 PM](https://user-images.githubusercontent.com/1111702/63748421-8534de80-c8d3-11e9-9327-6c673ee7f7df.png)

Did I missed or overlook something?

Many thanks for `glewlwyd` and your time on this.

**Comment by aviezab** [comment]
Hi @pixelblender 
Click the button I tagged bellow.
![image](https://user-images.githubusercontent.com/34294278/63767945-26825b80-c8f9-11e9-9520-be5d5db83e40.png)

and, after You logged in, then opened same page, don't forget to log out first, then log in again.

**Comment by pixelblender** [comment]
Hi @babelouest it does fix the issue. @aviezab thank you for the screenshot.

Currently password length is enforced at minimum 8 chars. How do I change this? Can't find relevant settings in the `glewlwyd.conf`.

Thank you guys!

**Comment by pixelblender** [comment]
Thank you for pointing to those `.js` files 👍 . Feel free to close this issue @babelouest 

Thank you for your time guys! :)

**Comment by babelouest** [comment]
@pixelblender , BTW, now have the possibility to configure the minimal length for clients and users passwords in the config.json file:
https://github.com/babelouest/glewlwyd/blob/master/webapp/config.json.sample#L6

The length must be at least 1 character though, but users can totally get rid of passwords in Glewlwyd if you want.

**Comment by pixelblender** [comment]
@babelouest awesome! thanks Nic!
