### ISSUE TITLE
Grant Access (Redirect Callback) Doesn't Work

### ISSUE THREAD

**Issue by aviezab** [babelouest/glewlwyd#63]
Hello there @babelouest . 

[![Screen Cast](https://s0.gifyu.com/images/glwdredir.gif)](https://s0.gifyu.com/images/glwdredir.gif)

So as the animated picture above, We can't redirect to callback URL after We successfully authenticated. We also can not input the redirect URL in client page using Administrator, is this a bug? After input at the client tab, the redirect URI textbox remains `NULL`.

![image](https://user-images.githubusercontent.com/34294278/63767744-a78d2300-c8f8-11e9-97a5-2251e293f93b.png)

How We do redirect in newest glewlwyd?

Also mention @nicabreon

**Comment by aviezab** [comment]
Hi @babelouest 
As I posted the issue, We did give the scope for client and also when hit the REST API.
![image](https://user-images.githubusercontent.com/34294278/63822695-638f3200-c97b-11e9-971a-66c53c39a8bc.png)

This is the REST API We saw from Dummy Web App
https://glwd:4593/login.html?response_type=code&client_id=client_grit&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Flogin%2Fauthorized&scope=client_grit


This is the dummy Web App We made for testing using Python 3, Flask and Flask Oauth Lib

```python
from flask import Flask, redirect, url_for, session, request
from flask_oauthlib.client import OAuth, OAuthException


GLEWLWYD_ID = 'client_grit'
GLEWLWYD_SECRET = 'gritxxx'


app = Flask(__name__)
app.debug = True
app.secret_key = 'gritxxx'
oauth = OAuth(app)

facebook = oauth.remote_app(
    'facebook',
    consumer_key=GLEWLWYD_ID,
    consumer_secret=GLEWLWYD_ID,
    request_token_params={'scope': 'client_grit'},
    base_url='https://glwd:4593',
    request_token_url=None,
    access_token_url='/api/glwd/token',
    access_token_method='GET',
    authorize_url='https://glwd:4593/login.html'
)


@app.route('/')
def index():
    return redirect(url_for('login'))


@app.route('/login')
def login():
    callback = url_for(
        'facebook_authorized',
        next=request.args.get('next') or request.referrer or None,
        _external=True
    )
    return facebook.authorize(callback=callback)


@app.route('/login/authorized') 
def facebook_authorized():
    resp = facebook.authorized_response()
    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    if isinstance(resp, OAuthException):
        return 'Access denied: %s' % resp.message

    session['oauth_token'] = (resp['access_token'], '')
    me = facebook.get('/me')
    return 'Logged in as id=%s name=%s redirect=%s' % \
        (me.data['id'], me.data['name'], request.args.get('next'))


@facebook.tokengetter
def get_facebook_oauth_token():
    return session.get('oauth_token')


if __name__ == '__main__':
    app.run()
```

**Comment by aviezab** [comment]
Hello @babelouest , I am sorry, I made myself not clear here.
What We want to achieve is:
We have Glewlwyd Web Client which does authenticate using password scheme. After `Grant Access`, the continue button doesn't return any access code so the Glewlwyd Server doesn't redirect to our web client back.

I will give credentials here as the site is also in development state.
Please You go to http://oauth.grit.id:5000/ and then the GLWD Web Client will show the GLWD Server's Login Page.
Login using `grituser` and password `password` , grant the access, and then continue. Then You will understand what We are facing.

Sorry for my bad language, and We really appreciate getting help from You 🙏. Thanks

**Comment by aviezab** [comment]
Hello @babelouest . We setted up the plugins, You can login as Admin by default username and password You've provided on https://oauth.grit.id:4593/ (there is other bug also, You will find You can not login unless using http://oauth.grit.id:5000/ then open the https://oauth.grit.id:4593/ again )

I have changed to https://oauth.grit.id:4593/api/glwd/auth/ just now, published at new web client http://oauth.grit.id:5001/ but the response is `File not Found ` 😂. 

> Obviously something isn't clear in the documentation, did you follow the installation and getting started documentation to help you configure Glewlwyd? Can you tell me if some parts should be enhanced?

Yes I think I will make the `Practical Documentation` including web client example, after our Web client and server work well so the newbie users do not need to read all documentation.

The explanation is detail, but the newbie user like me who "just know" how Oauth2 works will find it hard to use. Newbies just understand how to implement in simple steps.

**Comment by babelouest** [comment]
The first problem for your client lies in the configuration paragraph:

```
facebook = oauth.remote_app(
    'facebook',
    consumer_key=GLEWLWYD_ID,
    consumer_secret=GLEWLWYD_ID,
    request_token_params={'scope': 'client_grit'},
    base_url='https://glwd:4593',
    request_token_url=None,
    access_token_url='/api/glwd/token',
    access_token_method='GET',
    authorize_url='https://glwd:4593/login.html'
)
```

The parameters names are unusual but if I understand their configuration it should look like this:

```
facebook = oauth.remote_app(
    'facebook',
    consumer_key=GLEWLWYD_ID,
    consumer_secret=GLEWLWYD_ID,
    request_token_params={'scope': 'client_grit'},
    base_url='https://oauth.grit.id:4593/',
    request_token_url=None,
    access_token_url='/api/glwd/token',
    access_token_method='POST',
    authorize_url='/api/glwd/auth',
)
```

The second problem, the reason you have a `File not Found` error is because you didn't create an OAuth2 instance. You can find the install procedure in the [OAuth2](https://github.com/babelouest/glewlwyd/blob/master/docs/OAUTH2.md#installation) document, please use this.

If you improve the documentation, you should use the [Getting started](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md), [OAuth2](https://github.com/babelouest/glewlwyd/blob/master/docs/OAUTH2.md) and [OIDC](https://github.com/babelouest/glewlwyd/blob/master/docs/OIDC.md) files as starting point. If you find useful to make a new document file for beginners I'm ok but I wouldn't want to have the same explanation in multiple files. I prefer to move some paragraphs from existing documentation to new ones if necessary.

**Comment by aviezab** [comment]
Hello @babelouest Thank You for your help.
We have followed the documentation, and this is our settings:
![image](https://user-images.githubusercontent.com/34294278/64095383-d9830700-cd88-11e9-8a5f-c51ffa45dea8.png)

![image](https://user-images.githubusercontent.com/34294278/64095418-ef90c780-cd88-11e9-9afa-fc8f96689159.png)

![image](https://user-images.githubusercontent.com/34294278/64095478-164efe00-cd89-11e9-9713-14749fe7a7b1.png)

![image](https://user-images.githubusercontent.com/34294278/64095527-3383cc80-cd89-11e9-993e-1dd13646adad.png)

so far GLWD is best open source SSO Server We have found. But We nearly give up 🤣

Do You have nodeJS source code example for GLWD SSO client?
Thank You Nicolas

**Comment by babelouest** [comment]
Your glewlwyd configuration looks good, now it seems your python client is still buggy. According to your screenshots, the client config should look like this:

```
facebook = oauth.remote_app(
    'facebook',
    consumer_key=GLEWLWYD_ID,
    consumer_secret=GLEWLWYD_ID,
    request_token_params={'scope': 'client_grit'},
    base_url='https://oauth.grit.id:4593/',
    request_token_url=None,
    access_token_url='/api/oauth2p/token',
    access_token_method='POST',
    authorize_url='/api/glwd/auth',
)
```

Concerning nodejs OAuth2 client examples, I don't know any but a quick search online gives me some:
https://www.npmjs.com/package/client-oauth2
https://oauth.net/code/nodejs/

I also provided an example on how to configure glewlwyd to use with a taliesin server:
https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#use-case-configure-glewlwyd-to-authenticate-with-taliesin

**Comment by aviezab** [comment]
I want to ask, why our GLWD oauth2 plugin popup looks like this
![image](https://user-images.githubusercontent.com/34294278/64114181-8d4ebb80-cdb6-11e9-96bf-426c63db73fd.png)

rather than this as attached at Your documentation (https://github.com/babelouest/glewlwyd/blob/master/docs/OAUTH2.md) ?:
![image](https://user-images.githubusercontent.com/34294278/64114254-be2ef080-cdb6-11e9-82cb-ade2c16bace5.png)

The `authentication types` checklists is different.
@babelouest 

Thank You for JS example and Taliesin. Great work.
We are working to use other client until the client works.

**Comment by babelouest** [comment]
Glewlwyd 2 is still in Beta mode and changes often, so screenshots may not be accurate. Next step will be a Release Candidate (RC).
At that time I expect all the functionalities to be present. I'll use the opportunity to update the screenshots then.

If you're willing to help, you can read all the documentation and send feedbacks if you see something that should be improved or changed.

You can also provide translation for the Front-End. For now, only french and english languages are available.

To add new languages, you can start from the english resource file there: https://github.com/babelouest/glewlwyd/blob/master/webapp-src/locales/en/translations.json
translate all the entries into a different language, then make a pull request, I'll gladly add it to the repository!

**Comment by aviezab** [comment]
@babelouest We do, but just close it Nicolas.
We will investigate the client code further ourselves, thanks
