### ISSUE TITLE
Interaction with other oAuth providers?

### ISSUE THREAD

**Issue by KrishnaPG** [babelouest/glewlwyd#64]
This looks like a good work - thank you for sharing it.

Wondering how this server can be used in tandem with other oAuth providers. For example, consider this scenario:

- Lets say there is a website that relies on oAuth (supporting this server as one of the backends)
- lets say, the website also supports other oAuth backends (such as google etc.)
- now, assume one user logs in with google on the website.

What happens afterwards? Would an equivalent user be created on this Glewlwyd server? 

Also, is it possible to associate custom data with user login? For example, his configuration options or some other settings etc?

**Comment by babelouest** [comment]
Hello @KrishnaPG , thanks for the feedback!

Currently you can't connect with other OAuth providers but I'd like it to be possible in a near future.
Concerning your scenario, it's not possible.
But I thought of the following implementation:
- A user connects to a website which uses a Glewlwyd instance for authentication
- The website redirects the user to its Glewlwyd instance
- The user isn't registered in the Glewlwyd instance, so it clicks on the `register` button.
- There, the user can use several ways to authenticate to Glewlwyd, including:
  - Using a password
  - Using a Yubikey
  - Using a TOTP
  - Using a TLS certificate
  - Using another OAuth2 provider (Google, Microsoft, etc.)

In the registration process, the new user will register or more authentication schemes.

Also, about your last question, the admin can add as many new properties as it wants to all users: https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#add-or-update-additional-properties-for-users-and-clients

But when you talk about `configuration options or some other settings`, I'm not sure I understand. What would you need this for, can you give me more input or use case?

**Comment by babelouest** [comment]
Hello @KrishnaPG ,

Authentication via external OAuth2/OIDC providers is now available in Beta in the master branch, if you're willing to test it, you can follow the [Install documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#manual-install-from-source) and let me know if you have feedbacks.

**Comment by babelouest** [comment]
Glewlwyd 2.2.0 is [out](https://github.com/babelouest/glewlwyd/releases/tag/v2.2.0) now!
I'm closing this issue
