### ISSUE TITLE
Importing MariaDB/MySQL schema fails and proposed fixes..

### ISSUE THREAD

**Issue by vidcentum** [babelouest/glewlwyd#7]
**`mysql> SOURCE glewlwyd.mariadb.sql`**

Issue (1): Creation of g_reset_password failed complaining about invalid default value of grp_reset_at.
The fix could be allowing **TIMESTAMP NULL** as below.
-- Reset a user password
CREATE TABLE `g_reset_password` (
  `grp_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `grp_username` VARCHAR(128) NOT NULL,
  `grp_ip_source` VARCHAR(64) NOT NULL,
  `grp_token` VARCHAR(512) NOT NULL,
  `grp_enabled` TINYINT(1) DEFAULT 1,
  `grp_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `grp_reset_at` **TIMESTAMP NULL**
);
CREATE INDEX `i_g_reset_password_username` ON `g_reset_password`(`grp_username`);

Issue (2): Creation of g_refresh_token failed complaining about incorrect default values of grt_last_seen, grt_expired_at
The fix could be allowing **TIMESTAMP NULL** as below 

-- Refresh token table, to store a signature and meta information on all refresh tokens sent
CREATE TABLE `g_refresh_token` (
  `grt_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `grt_hash` VARCHAR(128) NOT NULL,
  `grt_authorization_type` INT(2) NOT NULL, -- 0: Authorization Code Grant, 1: Implicit Grant, 2: Resource Owner Password Credentials Grant, 3: Client Credentials Grant
  `grt_username` VARCHAR(128) NOT NULL,
  `grt_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `grt_last_seen` **TIMESTAMP NULL**,
  `grt_expired_at` **TIMESTAMP NULL**,
  `grt_ip_source` VARCHAR(64) NOT NULL,
  `grt_enabled` TINYINT(1) DEFAULT 1
);

Issue (3) This SQL statement appears after creation of g_access_token table. Just move the statement following the creation of g_refresh_token. It is a trivial fix though.
CREATE INDEX `i_g_refresh_token_username` ON `g_refresh_token`(`grt_username`);

#Issue (4). Creation of g_refresh_token failed complaining about incorrect default values of gss_last_seen, gss_expired_at.
The fix could be allowing **TIMESTAMP NULL** as below 

-- Session table, to store signature and meta information on session tokens sent
CREATE TABLE `g_session` (
  `gss_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `gss_hash` VARCHAR(128) NOT NULL,
  `gss_username` VARCHAR(128) NOT NULL,
  `gss_issued_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `gss_last_seen` **TIMESTAMP NULL**,
  `gss_expired_at` **TIMESTAMP NULL**,
  `gss_ip_source` VARCHAR(64) NOT NULL,
  `gss_enabled` TINYINT(1) DEFAULT 1
);
CREATE INDEX `i_g_session_username` ON `g_session`(`gss_username`);

After the above fixes, **`mysql> SOURCE glewlwyd.mariadb.sql`** went through.

**Comment by babelouest** [comment]
I'm nit sure of what you want to do with `TIMESTAMP NULL`, AFAIK, if you don't specify `NOT NULL` on a column, its value can be `NULL`, so I think the fix won't change anything. What is the problem you had when you imported the schema?

**Comment by vidcentum** [comment]
Thanks, @babelouest . When I imported the schema without the fix, the following errors occurred.
DB: MySQL.
...
ERROR 1067 (42000): Invalid default value for 'grp_reset_at'
ERROR 1146 (42S02): Table 'es-users.g_reset_password' doesn't exist
ERROR 1067 (42000): Invalid default value for 'grt_last_seen'
ERROR 1146 (42S02): Table 'es-users.g_refresh_token' doesn't exist
ERROR 1215 (HY000): Cannot add foreign key constraint
ERROR 1067 (42000): Invalid default value for 'gss_last_seen'
ERROR 1146 (42S02): Table 'es-users.g_session' doesn't exist

ERROR 1215 (HY000): Cannot add foreign key constraint
...
The following tables were not created 
g_refresh_token_scope
g_client_scope
g_access_token
g_refresh_token
g_session
g_reset_password

Then I executed each SQL statement separately to find out the issue. The error was due to default value of the TIMESTAMP field.

Further, I made explicit TIMESTAMP NULL

**Reference:**
> https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html
> TIMESTAMP Initialization and the NULL Attribute
> By default, TIMESTAMP columns are NOT NULL, cannot contain NULL values, and assigning NULL assigns the current timestamp. To permit a TIMESTAMP column to contain NULL, explicitly declare it with the NULL attribute.

By setting TIMESTAMP NULL, I was able to import schema successfully.

**Comment by babelouest** [comment]
yup, I see it, we probably have different configuration on our mariadb servers, but if you want to set the default value to NULL on timestamps, I suggest you use the more explicit `DEFAULT NULL` instead of `NULL` only. Can you update your pull request with that?

**Comment by vidcentum** [comment]
Sure, I have updated the file. Could you please check? 

Best Regards
Maruthi

**Comment by vidcentum** [comment]
@babelouest , I tested with TIMESTAMP DEFAULT NULL, and it did not fix the problem. Importing the schema failed again with DEFAULT NULL.
So, I had to revert it to TIMESTAMP NULL. 

You may please check the same in your MySQL servers.

**Comment by babelouest** [comment]
I may have a different configuration on my server because this problem never occurred, and I use this script a lot to test the application in a clean environment. But this syntax seems correct and fix your problem so I'm totally OK.

**Comment by vidcentum** [comment]
Thanks @babelouest , I will close the issue.
