### ISSUE TITLE
"Read only" in "Client data sources" is not honored by frontend

### ISSUE THREAD

**Issue by rurus9** [babelouest/glewlwyd#79]
**Describe the issue**
After adding "LDAP backend client module" with checked "Read only", in frontend still is "Read only": "No".
In database (I use mariadb as backend for glewlwyd config) I can see:
`> SELECT gcmi_module, gcmi_readonly FROM g_client_module_instance WHERE gcmi_module = 'ldap';
+-------------+---------------+
| gcmi_module | gcmi_readonly |
+-------------+---------------+
| ldap        |             1 |
+-------------+---------------+
1 row in set (0.001 sec)`

but in fronted still "Read only": "No", so everty time you have to remember to mark "Read only" again if you want to change configuration (without "Read only" you have to refill few more fields).

**To Reproduce**
Add "LDAP backend client module" with checked "Read only" and after save config check it again.

**Expected behavior**
Read only is honored by backend.

**Screenshots**
![Issue_read_only](https://user-images.githubusercontent.com/46960652/71615590-34e7c900-2bb2-11ea-9115-df2f9fc6aa68.png)

**System (please complete the following information):**
 - OS/Environment [Debian GNU/Linux bullseye]
 - Browser used [Mozilla Firefox 68.3.0esr]
 - Glewlwyd Version [2.0.0 docker image babelouest/glewlwyd:latest from 11/3/2019 Digest
9347e5910a70]

**Comment by babelouest** [comment]
Hello,

Thanks for noticing this issue.
fixed in https://github.com/babelouest/glewlwyd/commit/c009b65a0f7dc99c5565bf7e368a491d5cb0fb6d
