### ISSUE TITLE
Access profile endpoint in oauth2 plugin

### ISSUE THREAD

**Issue by heoyongun** [babelouest/glewlwyd#80]
**Describe the issue**
A clear and concise description of what the issue is, including a clear and concise title.

I have question. how to get login user [email or username, etc] info?

**To Reproduce**
If possible, post a sample code to reproduce the issue.

```
1. access_token pick up   it's ok
    const response = await axios({
      method: 'post',
      url: `http://localhost:4593/api/glwd/token`,
      headers: {
        accept: 'application/x-www-form-urlencoded'
      },
      data: qs.stringify({
        grant_type: `authorization_code`,
        code: `${requestToken}`,
        redirect_uri: `${redirect_uri}`,
        client_id: `${clientID}`
      })
    })

   const accessToken = response.data.access_token

2. profile request, response status is ok(200) but data is nothing.

    const session = await axios({
      method: 'get',
      url: `http://localhost:4593/api/glwd/profile/session`,
      headers: {
        Authorization: `Bearer ${accessToken}`
      },
    })
    
   //response.data === {} // no data.
```

**Expected behavior**

I was expecting.

response.data
```
{
 email: 'test1@gractor.com',
 username: 'test1'
}
```
But there is no data.  => {}

**Screenshots**

**System (please complete the following information):**
 - OS/Environment [e.g. Debian Stretch, Ubuntu 19.04]
 - Browser used [e.g. Mozilla Firefox 69, Chrome 77, lynx 2.9]
 - Glewlwyd Version [e.g. 2.0.0, 1.4.9]
 - Source installation [e.g. Distribution package, GitHub package, build from source]
 - If applicable, what option did you use to build Glewlwyd

ubuntu 19.04
Chrome 79.0.3945.88
glewlwyd 2.x

**Additional context**

**Comment by babelouest** [comment]
Hello @heoyongun ,

If I understand correctly your issue, you need to access the profile endpoint which is located at `http://localhost:4593/api/glwd/profile`, not `http://localhost:4593/api/glwd/profile/session`.

This endpoint will return a response of the following format:

```JSON
{ 
  "username": "user1", 
  "name": "Dave Lopper 1", 
  "email": "dev1@glewlwyd" 
}
```

**Comment by heoyongun** [comment]
I was expecting. 
response.data
```
{
 email: 'test1@gractor.com',
 username: 'test1'
}
```
But there is no data. => {}

![스크린샷, 2020-01-02 11-47-38](https://user-images.githubusercontent.com/6076067/71653072-d49d8680-2d6d-11ea-9338-a93b469c4b19.png)

![스크린샷, 2020-01-02 11-47-42](https://user-images.githubusercontent.com/6076067/71653077-d9fad100-2d6d-11ea-9cb3-ee10444f769b.png)

![스크린샷, 2020-01-02 11-47-55](https://user-images.githubusercontent.com/6076067/71653080-dcf5c180-2d6d-11ea-9780-69b52592c49f.png)

**Comment by heoyongun** [comment]
> Hello @heoyongun ,
> 
> If I understand correctly your issue, you need to access the profile endpoint which is located at `http://localhost:4593/api/glwd/profile`, not `http://localhost:4593/api/glwd/profile/session`.
> 
> This endpoint will return a response of the following format:
> 
> ```json
> { 
>   "username": "user1", 
>   "name": "Dave Lopper 1", 
>   "email": "dev1@glewlwyd" 
> }
> ```


http://localhost:4593/api/glwd/profile/session

I was expecting.
response.data
```
{
 email: 'test1@gractor.com',
 username: 'test1'
}
```
But there is no data. => {}

![스크린샷, 2020-01-02 11-47-38](https://user-images.githubusercontent.com/6076067/71653176-5e4d5400-2d6e-11ea-97e4-67e895174153.png)

![스크린샷, 2020-01-02 11-47-42](https://user-images.githubusercontent.com/6076067/71653178-62797180-2d6e-11ea-8090-131469f3a868.png)

![스크린샷, 2020-01-02 11-47-55](https://user-images.githubusercontent.com/6076067/71653179-660cf880-2d6e-11ea-9163-7219f22b37d3.png)

**Comment by heoyongun** [comment]
yes. working for me.
thank you.
