### ISSUE TITLE
[Issue] redirect Issue

### ISSUE THREAD

**Issue by heoyongun** [babelouest/glewlwyd#86]
**Describe the issue**

It works differently than I intended.

**To Reproduce**

```
<!DOCTYPE html>
<html>

<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Node oAuth2 Example</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
        <!-- <script src="main.js"></script> -->
</head>

<body>
        <a href="http://192.168.1.195:4593/api/glwd/auth?response_type=code&scope=foo%20bar&client_id=client_1&redirect_uri=http%3A%2F%2F192.168.1.195%3A8080%2Foauth%2Fredirect">Login with Glewlwyd</a>
</body>

</html>
```

**Expected behavior**
I Expect this.
![스크린샷, 2020-01-06 11-24-44](https://user-images.githubusercontent.com/6076067/71791169-43812500-3077-11ea-989e-f22f8c9a82c5.png)

But result is this.
![스크린샷, 2020-01-06 11-26-13](https://user-images.githubusercontent.com/6076067/71791194-657aa780-3077-11ea-9317-bc2e44764cea.png)

**Screenshots**

**System (please complete the following information):**
ubuntu 19.04
Chrome 79.0.3945.88
docker image glewlwyd 2.x

**Additional context**
request url 

```
http://192.168.1.195:4593/api/glwd/auth?response_type=code~~~~~
```
I expect. redirect url is

```
http://192.168.1.195:4593/login.html?client_id=client_1&scope~~~~~
```

but result is
```
http://localhost:4593/login.html?client_id=client_1&scope~~~~~
```

**Comment by babelouest** [comment]
Hello @heoyongun ,

It looks like you use the docker image without changing the config files:
https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#docker

Check the paragraph called `Customize configuration files without rebuilding the docker image` to use a personalized `glewlwyd.conf` file.

You'll need to update your [external url](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#external-url) parameter.

**Comment by heoyongun** [comment]
Thank you. work for me
