### ISSUE TITLE
[Issue] chrome and firefox different view.

### ISSUE THREAD

**Issue by heoyongun** [babelouest/glewlwyd#87]
**Describe the issue**
firefox radio button display ok.
chrome radio button display is block.

**To Reproduce**

**Expected behavior**

**Screenshots**
Firefox diplay
![스크린샷, 2020-01-06 17-14-49](https://user-images.githubusercontent.com/6076067/71805173-e2724500-30a8-11ea-9c46-145ea7820b09.png)
![스크린샷, 2020-01-06 17-16-38](https://user-images.githubusercontent.com/6076067/71805174-e2724500-30a8-11ea-8aee-746a8cacd619.png)

Chrome display
![스크린샷, 2020-01-06 17-21-33](https://user-images.githubusercontent.com/6076067/71805240-18172e00-30a9-11ea-886a-e67b8547c289.png)

**System (please complete the following information):**
ubuntu 19.04
Chrome 79.0.3945.88
firefox 71.0
docker image glewlwyd 2.x

**Additional context**

**Comment by babelouest** [comment]
Hello,

Yes this has been fixed in a recent commit in the master branch. If you can't wait for the next release, you can build your own docker image as explained in [the documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#docker-image-builder)
