### ISSUE TITLE
I can obtain token in oauth2 Client Credentials flow for non confidential user

### ISSUE THREAD

**Issue by rurus9** [babelouest/glewlwyd#88]
**Describe the issue**
User without marked "Confidential" checkbox can obtain proper token in oauth2 Client Credentials flow

**To Reproduce**
Start new docker instance 
`docker run --rm -it -p 4593:4593 src:20200110`
Add client to default "Database backend user module" (I only filled "Client ID": test1, "Name": test1, "Password", "Scope": openid and "Authorization types": client_credentials.
Confidential is not marked).

Also add oauth2 plugin (I only filled name: "oauth2", display name: "oauth2", and Tokens signature - JWT type: "RSA", Key size: "512 bits", and public and private key).

I can get proper token (in oauth2 Client Credentials flow) for this client.

**Expected behavior**
You can't get token in this flow for client which isn't confidential.

**Screenshots**
![Client_non_confidential](https://user-images.githubusercontent.com/46960652/72154834-fd4aff00-33b1-11ea-8442-3769f9e956db.png)

**Comment by babelouest** [comment]
Hello @rurus9 ,

Thenka for reporting the issue, this has been fixed in https://github.com/babelouest/glewlwyd/commit/93301a2529e106315c6a1ab36cfd1ac0ac3ffb8f , can you check the new version?

**Comment by rurus9** [comment]
Yes, now (i built docker today) it's OK.
Thank you
