### ISSUE TITLE
Server core dumps in user.c and client.c 

### ISSUE THREAD

**Issue by vidcentum** [babelouest/glewlwyd#9]
LDAP was not configured. Set ldap_auth = false in the config file.
While login from the webapp, get_user (...) [file: user.c] is called that access ldap resources and thus leasing to a core dump.

I applied a possible quick fix in the user.c, get_user (...) function as below before accessing either LDAP, database sources.
```
if (config->has_auth_ldap && search_ldap) {
      j_user = get_user_ldap(config, login);
  }
if (config->has_auth_database && !check_result_value(j_user, G_OK) && search_database) {
      json_decref(j_user);
      j_user = get_user_database(config, login);
}
```
I am able to access the webapp pages after the fix.

**Comment by babelouest** [comment]
So I was able to fix this bug and several others, in fact client authentication was not good at all in ldap, and if you had only one backend available (ldap or database), there was several problems like the one you pointed out. I also made a modification on the database structure, you must reapply it, sorry: https://github.com/babelouest/glewlwyd/commit/d00f37dd9443f33e614bd3e8d6e06648813a9170

Let me know if this fix this issue's problems for you.

**Comment by vidcentum** [comment]
No problem at all @babelouest . I can take new code and build the server. Keep you updated on the findings. 

Once again thank you for quick fixes. 

Best Regards
Maruthi

**Comment by vidcentum** [comment]
Closing the issue.

**Comment by babelouest** [comment]
No problem, thanks for the feedbacks!
