### ISSUE TITLE
Automated integration tets suite for Glewlwyd

### ISSUE THREAD

**Issue by etuttle** [babelouest/glewlwyd#90]
Glewlwyd is exciting to me because of the feature set and it seems to fill a void in the open source marketplace.   I am concerned however about the difficulty of maintaining interoperability with the hundreds of apps being used in corporate environments makes it a non-starter for potential adopters.  If I were a decision maker looking at Glewlwyd, I would need assurance that it works out of the box with whatever Service Providers I'm interested in protecting.

My adventure getting it to work with Jenkins was rocky to say the least!

Have you considered developing an automated interoperability suite that would put such concerns to rest?

Such a suite could start small.  If the framework was in place, it shouldn't be hard for contributors to add to the suite.

(I have the same thought about automated fuzz testing / static code analysis, but that is a separate issue for now..)

Any plans in this direction?

**Comment by babelouest** [comment]
Hello @etuttle ,

Thanks for your enthusiasm with Glewlwyd!

> it seems to fill a void in the open source marketplace.

I wouldn't know about that, I make Glewlwyd to fill my void of a lightweight authentication server and for fun.
There is Keepass and Gluu at least, but they were too large to fit in my home-lab.

> I am concerned however about the difficulty of maintaining interoperability with the hundreds of apps being used in corporate environments makes it a non-starter for potential adopters.

Although I understand what you mean deep down, my first answer is to say that Glewlwyd relies on public standards such as [OAuth2](https://tools.ietf.org/html/rfc6749) and [OpenID Connect](https://openid.net/specs/openid-connect-core-1_0.html).

I expect Glewlwyd to be as close as possible to those standards. So I'd say that's the first step and the biggest for potential adopters to make their own choice.

> Have you considered developing an automated interoperability suite that would put such concerns to rest?

I haven't yet. Not that I don't want to, it's more that I never had the need. So far, the clients I use are also my own.
I'm interested in the idea though! What I could provide is for example a docker image with a documented to help people using it to run their tests, something like:
- How-to build the docker image
- Server setup with the schemes installed, the scopes installed and what scheme is linked with what scope
- Setup for OAuth2 and OIDC plugins, especially public and private keys
- List of users available, their scopes and their passwords
- List of clients available, with different use-cases

> (I have the same thought about automated fuzz testing / static code analysis, but that is a separate issue for now..)

The test cases and automated part would be for the client, but I could provide an easy-to-run normalized server to help build such test cases.

**Comment by etuttle** [comment]
Well I admire your DIY spirit if you're building Glewlwyd for a home lab!

True, there are other open source options.  My words weren't very well chosen.  This project stands out because of the particular feature set (making password-less a possibility) and it is so small and focused.  Compared to, say, keycloak.

You've done a great job with your docs already.  If interop isn't a priority for the project, I wouldn't mind if you want to close this ticket.  It's a "3rd party opportunity" :)

**Comment by babelouest** [comment]
> If interop isn't a priority for the project, I wouldn't mind if you want to close this ticket

On the contrary (I probably wasn't clear myself), interop is important for me, that's why I came with the solution of a documented docker image to run automated integration tests.

What do you think about the idea of the docker image to run integration tests?

> Compared to, say, keycloak

My bad, I meant keycloak on my message, not keepass which is another tool for a different purpose :p

**Comment by etuttle** [comment]
👍 for running integration tests with docker!  My Glewlwyd + Jenkins playground is running on minikube on my Mac, which I prefer over plain old docker.  But docker is a start.

**Comment by babelouest** [comment]
The docker image is a quick win for docker users but basically it's just a specific `glewlwyd.conf` file and a SQL script to run before, so you can have the normalize glewlwyd for integration tests in any environment you would like it to be.

**Comment by babelouest** [comment]
The install documentation has been updated to create a Glewlwyd instance for CI tests. The documentation is available here: https://github.com/babelouest/glewlwyd/blob/master/docs/INSTALL.md#running-glewlwyd-in-test-mode-for-integration-tests

If you can give me feedbacks based on this new documentation, that would be much appreciated!
