### ISSUE TITLE
[Question] A way to get "exp" and "nbf" claims in JWT token payload

### ISSUE THREAD

**Issue by rurus9** [babelouest/glewlwyd#99]
When I get JWT token (I use Client Credentials Grant), payload is:
`"client_id":"my_client_id","expires_in":3600,"iat":1580717452,"salt":"SaLt","scope":"list of scopes","type":"client_token"`

Unfortunelly, in some products (like Kong Gateway with JWT plugin: https://docs.konghq.com/hub/kong-inc/jwt/) only way to check JWT token lifetime is to use "exp" and "nbf" claims. Is any way to receive these claims in token payload?

**Comment by babelouest** [comment]
Hello,

That can be added to the access token granted to the client. The claim `exp` will simply be `iat+expires_in`, but concerning `nbf`, since glewlwyd has no specific property for that, I would simply set it the same as `iat`. Is that ok?

**Comment by rurus9** [comment]
@babelouest  - yes, I considered it this way. It is simple and safe, I think.

**Comment by babelouest** [comment]
@rurus9 I've added `exp` and `nbf` properties to access tokens JWT payload, both for users and clients JWTs, in both OAuth2 and OIDC plugins in the last commit: https://github.com/babelouest/glewlwyd/commit/6cdd0a296b1f061992f02c7a6d66152c7366ff14
Can you test it and give me feedbacks on it? You can reopen this issue if needed.

**Comment by rurus9** [comment]
Oh yeah, I built docker image today and after deploying:
`{"client_id":"my_client_id","exp":1580806962,"expires_in":3600,"iat":1580803362,"nbf":1580803362,"salt":"SalT","scope":"client scopes","type":"client_token"}`
Thank you!
